### ISSUE TITLE
Up-scaled logo and box image sizes for games.

### ISSUE THREAD

**Issue by wdziemia** [justintv/Twitch-API#117]
Image sizes (large, medium, small) are not different resolution. All images are the same resolution but scaled up causing blur before they are returned to client. Wouldn't it make more sense to have a Hi-Res image and then scale it down to its appropriate size?

Also, when a box cover does not exist, the 404 image returned is always medium sized, regardless of if you requested for a small or large image.

**Comment by Shobba** [comment]
Is there any chance to get high res boxart from the API?

**Comment by scagood** [comment]
The box art all seems fine to me, how large are you talking?
```
http://static-cdn.jtvnw.net/ttv-boxart/[name of game].jpg
```
gets you the original box art image from the from the twitch cdn for example:
```
http://static-cdn.jtvnw.net/ttv-boxart/Counter-Strike:%20Global%20Offensive.jpg
```
gets the CSGO box art

**Comment by Shobba** [comment]
Oh okay, thanks! I just checked the /search/games API, didn't know I just can remove the resolution from the URL.
```
"box": {
            "large": "http://static-cdn.jtvnw.net/ttv-boxart/Gaming%20Talk%20Shows-272x380.jpg",
            "medium": "http://static-cdn.jtvnw.net/ttv-boxart/Gaming%20Talk%20Shows-136x190.jpg",
            "small": "http://static-cdn.jtvnw.net/ttv-boxart/Gaming%20Talk%20Shows-52x72.jpg",
            "template": "http://static-cdn.jtvnw.net/ttv-boxart/Gaming%20Talk%20Shows-{width}x{height}.jpg"
        }
```

**Comment by scagood** [comment]
I just go with trial and error with random poking and prodding every now and again, then if all else fails ask someone who may know :smile:

**Comment by Fugiman** [comment]
The `template` parameter is intended to allow you to retrieve the image in whatever resolution you want, by replacing `{width}` and `{height}` with the dimensions you need.
