### ISSUE TITLE
Allow cross origin [CORS]

### ISSUE THREAD

**Issue by tetreum** [justintv/Twitch-API#133]
Hi, my app is JS only and twitch api doesn't have cross origin header, so i can't make requests.
header('Access-Control-Allow-Origin:*');

**Comment by richardbrammer** [comment]
How is it possible to use **PUT** with a JSONP call without CORS support?

This is needed to update the channel status as described here: 
https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#put-channelschannel

**Comment by bashtech** [comment]
You can use the `_method=PUT` query string param to specify that it is a PUT request.

**Comment by richardbrammer** [comment]
Thanks @bashtech , using _method=PUT works just fine!

**Comment by pburtchaell** [comment]
Would really appreciate CORS support here. In most cases it is a one line code change!

**Comment by noinkling** [comment]
Has CORS support been added? `Access-Control-Allow-Origin: *` seems to be set now and I can get data fine without JSONP.

**Comment by neolectron** [comment]
i still have the CORS error.

**Comment by vybz1000** [comment]
Any news on this? My OPTIONS call gets....

`access-control-allow-headers:Accept, Authorization, Client-Id, Twitch-Api-Token, X-Forwarded-Proto, X-Requested-With, X-Csrf-Token, Content-Type`

but no X-**X**srf-Token

**Comment by vybz1000** [comment]
@3ventic may I direct you to https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection. An angular default.

**Comment by freaktechnik** [comment]
I don't see how XSRF tokenas are related to CORS nor are helpful for a REST API.

**Comment by trumpi** [comment]
The Twitch API doesn't use cookies to authenticate, so a XSRF token is not necessary.

**Comment by billygerhard** [comment]
I am going to +1 this as well. Yes, we can use JSONP, but that causes a lot of overhead to have to keep adding extra code for every time you want to use the API in the application, instead of just using the API as is to bypass a simple feature for Twitch to add. And as stated above, you can support and serve both options to developers at once. You don't need to make a hard switch to support CORS.

**Comment by bashtech** [comment]
All `/kraken/` endpoints support CORS. This is a really old issue that should probably be closed.
