### ISSUE TITLE
Improvement: Allow control of flash stream player via JS

### ISSUE THREAD

**Issue by lwansbrough** [justintv/Twitch-API#145]
I'd love to be able to disable the default chrome for the video player (doesn't match my site) in favour of using my own buttons. Of course the Twitch branding would remain so there's no loss there, but being able to do `video.volume(50)` or `video.start()` would be really great.

**Comment by Syrah-NL** [comment]
In reply to rvulpescu:
Although this command is not listed under functions on the previously mentioned Github page, I can confirm that the following JS function works:

setQuality('Mobile');

You can change 'Mobile' to the other available qualities as well. I'm still experimenting, but it seems you have to setQuality() before you loadStream()...
