### ISSUE TITLE
Twitch Player API not respecting "auto_play=false"

### ISSUE THREAD

**Issue by bashtech** [justintv/Twitch-API#159]
The [Twitch Player API](https://github.com/justintv/Twitch-API/blob/master/player.md) docs defines an `auto_play` flashvar which is not respected when set to false.

Example: http://jsfiddle.net/bgeorge/8yuny/

A similar result can be achieved by using the `player.pauseVideo()` method but interacting with Javascript is not always ideal.

EDIT: Also not working when using the embed HTML provided by the Share button on the channel page. Ex: http://jsfiddle.net/bgeorge/bdF5B/

**Comment by Glaived** [comment]
Apparently not, according to my test, the problem comes when the player is loaded, the stream is offline, then online is the player loads the stream when it should not.

However, if the player is charged while the stream was already online, he did not start playing
