### ISSUE TITLE
Add started_at for a stream object in /streams

### ISSUE THREAD

**Issue by ghost** [justintv/Twitch-API#196]
There doesn't seem to be an obvious way to find out when a stream started, except by polling the API every X seconds for new streams and marking those down.

**Comment by vav17** [comment]
Indeed, I think this is a really basic function that should be added!

**Comment by Fugiman** [comment]
As you can see by the referenced commit, `created_at` was added last year. Enjoy!

**Comment by vav17** [comment]
Oh I oversaw this, Sorry! okay so I have "created_at":"2015-08-09T17:21:14Z" so how is this formatted? Year-month-day-??-hour-minutes-seconds?-?? and what timezone is this based on or does either the T or the Z tell me this?
-vav17

**Comment by night** [comment]
https://en.wikipedia.org/wiki/ISO_8601

**Comment by vav17** [comment]
Thanks for the quick responces!
