### ISSUE TITLE
Add getter/setter of currentTime for the Twitch API player

### ISSUE THREAD

**Issue by Eksrow** [justintv/Twitch-API#209]
The documentation doesn't seem to specify a way to get the current time from the player.

Proposed:
player.currentTime() -> returns the number of seconds since video start.

and

player.currentTime({seconds : N}) -> sets the player's current time and returns the current number of seconds since video start

OR

player.seek(seconds) -> advances(or if negative; reverses) the player N seconds and returns the current number of seconds since video start

**Comment by denisvlr** [comment]
Jumping on this issue, is there currently a way to get and/or set the currentTime of the video?

Thanks!

**Comment by scien** [comment]
for seeking you can use `videoSeek(seconds)` where `seconds` is the number of videos into the video to go (as described on https://github.com/justintv/Twitch-API/blob/master/player.md)

if you're using VODs you can use the secretive `getVideoTime()`. unfortunately for live streams this always returns `0`.

twitch - getVideoTime() reporting the current amount of time a stream has been live for would be excellent.

**Comment by scien** [comment]
twitch - might also want to add `getVideoTime` to the player api docs - https://github.com/justintv/Twitch-API/blob/master/player.md

**Comment by jasongornall** [comment]
+1

**Comment by SJAnderson** [comment]
+1

**Comment by jasongornall** [comment]
These both exist already. getCurrentTime() and seek(): https://github.com/justintv/Twitch-API/blob/master/embed-video.md#player-status
