### ISSUE TITLE
Notification of stream changes via webhooks

### ISSUE THREAD

**Issue by lwansbrough** [justintv/Twitch-API#211]
Knowing when a user goes online is a big deal, and it doesn't look like the API has this ability yet. It would be great to have an endpoint that we could POST a webhook URL to, which would return us the current state of whatever we're requesting as well as a promise to post updates to the webhook URL for X amount of time (say... 30 days).

For example, if we could 

```
POST https://api.twitch.tv/kraken/streams/test_channel
{ "webhook": "http://example.com/twitch/stream/test_channel", "interval": 60 }
```

Twitch would then respond something like this:

```
{
    "data": { [stream data here] },
    "promise": {
        "webhook": "http://example.com/twitch/stream/test_channel",
        "interval": 60,
        "expires": 2592000
    }
}
```

T'would be nice.

**Comment by fcarentz** [comment]
Is there a limit to number of channels you can provide via this method? What if we had 1000 channels to batch, would that be a problem?

**Comment by jwmalara** [comment]
Looks like its paged based on 'limit', chunks of 100 being the max.

**Comment by aequasi** [comment]
Are webhooks still not planned? They tend to be more efficient on the server and less of a headache for users.

**Comment by StefanJanssen95** [comment]
Webhooks would make everything a lot easier indeed.

**Comment by 4c74356b41** [comment]
man, no webhooks, is this 2009?

**Comment by ivandardi** [comment]
Even Picarto has [webhooks!](https://docs.picarto.tv/api/#/webhook)

**Comment by l3d00m** [comment]
Is there any update as the issue is now over 3 years old and webhooks are still highly relevant?

**Comment by neolectron** [comment]
up

**Comment by 3ventic** [comment]
This repository isn't used anymore. Should use the [dev forums](https://discuss.dev.twitch.tv/) instead.

**Comment by l3d00m** [comment]
And [here](https://discuss.dev.twitch.tv/t/webhooks-implementation/1644) is a relevant thread from Februrary '15. There are still no plans to implement it.

**Comment by 4c74356b41** [comment]
i stopped using twitch altogether because of this ;)

**Comment by neolectron** [comment]
Nvm its stupid, we'll keep spamming api calls just to test a truthy value. Gj twitch. Scaling at his finest.
