### ISSUE TITLE
Get online channels

### ISSUE THREAD

**Issue by noh4ck** [justintv/Twitch-API#249]
So there is a way to get all channels that a user is following without authentication:
```
GET /users/:user/follows/channels
```
But to get the online channels the user have to be authenticated. What is the reason for this?
It's easy to work around by just looping through all the channels a user is following and check if they're online, but this could be really slow, and seems unnecessary.

It would be nice to have an option to sort by online channels. ex:
```
GET /users/:user/follows/channels?sort=online
```

I'm sorry if I overlooked the actual way of doing this and that this is already possible.

**Comment by RenaKunisaki** [comment]
This seems like an obvious oversight that wouldn't be too difficult to fix. I'm following 98 channels. If I want a list of all channels I'm following that are currently live, that takes 99 API requests - one for the follow list, and one for *each channel* to ask if it's live. If the `channel` field of the `follow` response just included the channel's `stream` field (like you get from https://api.twitch.tv/kraken/streams/test_channel), or even just a flag telling if the channel is live, it would only take a single request.

**Comment by freaktechnik** [comment]
@RenaKunisaki Actually, you can request multiple streams in one request with streams/?channel=onechannel,secondchannel and so on. So it's two calls.

**Comment by RenaKunisaki** [comment]
That is a lot better. Where is that documented? How many channels can I request at once?

**Comment by 3ventic** [comment]
@RenaKunisaki It's in parameters under [GET /streams](/v3_resources/users.md#get-streamsfollowed) documentation. It'll return up to the limit. Though for getting followed channels, [GET /streams/followed](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed) is likely a better option.

**Comment by RenaKunisaki** [comment]
Aha, thanks. I hadn't looked closely enough at that.

/streams/followed would be better, but that requires authentication, which would make the app more complicated to use.
