### ISSUE TITLE
The redirect when clicking on the embedded stream does more bad than good.

### ISSUE THREAD

**Issue by magnusfoldager** [justintv/Twitch-API#253]
Hello!

I have created a topic about this on the Twitch Dev Discussion board here:

http://discuss.dev.twitch.tv/t/the-embedded-player-and-the-click-on-video-redirect/1100/

I was told that I may have bigger success submitting an issue here. A quick reference of what the topic is about: Whenever you click the video/stream on the embedded player, you are redirected to the Twitch channel page. This is frustrating, since many users using the embedded player has a reason to, such as live stats, a more information, a more private/civilized chat et cetera. I suggest that a better way to create a redirect would be to use the Twitch logo in the top right of the embedded player, and instead have clicking once on the stream do either nothing, or pause the stream. Twice should do full screen like on the main site.

Everyone I have talked to has agreed to this being an issue, and I believe that it should be looked into. Thank you very much for reading.

**Comment by scien** [comment]
+1

**Comment by SJAnderson** [comment]
+1

**Comment by jasongornall** [comment]
+1

**Comment by rezonant** [comment]
+1

**Comment by Marioario** [comment]
@magnusfoldager can close? new embed player only redirects when clicking on the twitch banner
