### ISSUE TITLE
/streams/followed doesn't require user_read scope; docs say it does

### ISSUE THREAD

**Issue by yoshifan** [justintv/Twitch-API#261]
This is true for `/streams/followed` and v3's `/videos/followed`. The documentation says "Authenticated, required scope: user_read" for both of these, but you can authenticate without specifying any scopes and they will work fine.

Being a novice, this actually got me stuck for a bit. The first authenticated calls I worked with were `/streams/followed` and `/videos/followed`, and I noticed I didn't need to specify any scopes, so I thought `user_read` was a default scope or something. When I later tried the URL `/user`, it took me a little while to realize that this one DID require me to specify `user_read`.

**Comment by RenaKunisaki** [comment]
https://api.twitch.tv/kraken/streams/followed in my browser gives me:

```
{"error":"Unauthorized","message":"Token invalid or missing required scope","status":401}
```

even though I *am* logged in. (I suppose being logged in isn't the same as being authenticated with the API?) So this seems to be fixed (or broken in some other way).

**Comment by TournyMasterBotCurse** [comment]
That's not how you pass an oauth token. You need to read authorization.md, and you can test with a tool like fiddler.

**Comment by RenaKunisaki** [comment]
Right, so this is probably fixed then.

**Comment by freaktechnik** [comment]
Not necessarily. This is about scopes, not just needing to be authorized.

**Comment by yoshifan** [comment]
Update: Starting around 2016/04/29, it seems that `/streams/followed` started requiring the `user_read` scope. So that's consistent with the [documentation](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed) now.

However, `/videos/followed` seems unchanged: it doesn't require `user_read` and the [documentation](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-videosfollowed) still says it does.
