### ISSUE TITLE
auto_play=false not respected in embed player

### ISSUE THREAD

**Issue by Jaxel** [justintv/Twitch-API#289]
Twitch finally added an IFrame based embed code; which is great for those who use HTTPS.

However, I can't seem to figure out how to disable auto-play on the new iframe embed code.

**Comment by conradmuan** [comment]
+1 we use iframe embeds for our mobile users. Unfortunately, it frustrates users across mobile and desktop because videos autoplay. Is there an ETA for this request?

**Comment by Fasani** [comment]
You could Just put a place holder there with a huge play button, on click load the stream iframe...

**Comment by conradmuan** [comment]
good idea @Fasani

**Comment by cmillward** [comment]
This is an issue with the player not respecting the auto_play=false argument. It's on the queue to be fixed, but no ETA. I'm going to make this the main issue to track this on, and edit the title.

Thanks.

**Comment by englercj** [comment]
Curious if there has been any movement on this at all? Would be nice to use the iframe embed without autoplaying.

**Comment by Lighnat0r** [comment]
For anyone who runs into this issue, you can use the following hack to work around the bug and make auto_play=false usable.
This works because isPaused() does return the right value even though the player doesn't respect it.

```javascript
$(function () {
	window.onPlayerEvent = function (data) {
		data.forEach(function(event) {
			if (event.event == "videoPlaying") {
				var player = $("#twitch_embed_player")[0];
				if (player.isPaused()) {
					player.pauseVideo();
				}
			}
		});
	}
});
```
(adapted from https://github.com/justintv/Twitch-API/blob/master/player.md#example-code)

Needless to say the video does play for a fraction of a second before the event fires and it's paused again.

**Comment by lamoni** [comment]
Is there any update on this?  Seems pretty critical.

**Comment by jasongornall** [comment]
bumping this still seems to be a issue

**Comment by SJAnderson** [comment]
bumping

**Comment by scien** [comment]
+1

**Comment by ebronnum** [comment]
Surprising that this remains unfixed for so long. Any updates?

**Comment by Marioario** [comment]
+1

**Comment by srimola** [comment]
+1

**Comment by perich** [comment]
+1

**Comment by appleseedexm** [comment]
+1

**Comment by BoldBigflank** [comment]
+1

**Comment by SiteSplat** [comment]
@Jaxel @lamoni Critical for sure and its quite annoying. Its been 6 over months already :-/ Autoplay still kicks in and ignore the off parameter.

**Comment by Jaxel** [comment]
@SiteSplat there are bugs in the twitch API that haven't been fixed in 2 years. To this day, you can not properly embed a twitch stream on your website if you use https/ssl.

I no longer expect anything to be fixed on Twitch these days.

**Comment by tylermakes** [comment]
+1

**Comment by SiteSplat** [comment]
@Fugiman Can you comment on this please?

**Comment by caeleel** [comment]
@jaxel we're on the cusp of releasing a new player, and will have autoplay issues sorted out when we release. We understand that it's been an unreasonably long time fixing this, and apologize.

**Comment by jordanorelli** [comment]
this is still a thing huh

**Comment by bashtech** [comment]
Have you tried the new embed player (
https://github.com/justintv/Twitch-API/blob/master/embed-video.md)?

**Comment by BoldBigflank** [comment]
@bashtech That's the documentation, which explains the proper behavior. It has never worked in practice.

**Comment by bashtech** [comment]
I ask because that player was released just recently, way after the issue
was created. Unfortunately I'm on a mobile devices and cannot test it
myself.

**Comment by ebronnum** [comment]
From my brief testing, the new player continues to ignore "autoplay=false".

**Comment by Jaxel** [comment]
The &autoplay=false tag is only respected for VIDEOS, not for live streams...

Man, this is pathetic. Twitch unveils yet another new embed code... still doesn't respect autoplay settings... still doesn't support SSL.

**Comment by Fugiman** [comment]
We're working on adding support for `autoplay=false`, and will close the issue when that's completed. SSL is a completely different and much more complicated matter, but one we are working on addressing.

**Comment by jordanorelli** [comment]
:+1: thanks!

I want to add this to the dotabuff forums but the docs for the old player were deleted, so it looks like the support is ending for the old player. I'm wary of adding the old player since it's at EOL, but a player without autoplay is untenable since there may be multiple embeds on one page.

**Comment by caeleel** [comment]
This is now working!

**Comment by Oted** [comment]
I am still experiencing the same issue, the player does not respect autoplay=false. 
Is it only me? Can someone point me to the documentation of how to properly make the player not autoplay please.

**Comment by MellowNebula** [comment]
@Oted Works for me. 
See: https://github.com/justintv/Twitch-API/issues/505#issuecomment-194739376

**Comment by Oted** [comment]
@MellowNebula my bad, was still passing it in to the iframe. 
thanks :+1:
