### ISSUE TITLE
Content-Type response header for emoticons is text/html

### ISSUE THREAD

**Issue by martijnhoekstra** [justintv/Twitch-API#293]
the /kraken/chat/emoticons endpoint responds with a  "text/html" Content-Type header, while the content is json.

**Comment by Bigmacbook** [comment]
yeah this is causing a problem for me because i can't use jquery to request the emoticons

**Comment by bashtech** [comment]
You really should be using `emoticon_images` now: https://api.twitch.tv/kraken/chat/emoticon_images
