### ISSUE TITLE
IRC commands and messages limit to the server or to the channel?

### ISSUE THREAD

**Issue by Defman21** [justintv/Twitch-API#305]
Sorry maybe I'm asking a stupid question, but...
20 commands/messages is limit to the global server or to the specific channel? Just in case if my bot will be used by more than one channel - he can be banned very fast?

**Comment by AnUnknownMiner** [comment]
I don't know about the server/channel part, but if your bot is a Modertor in said channel. The rate is 100 commands/messages iirc. So that probably means 20 cmds/mess in a non-modded channel.

**Comment by Defman21** [comment]
Thanks a lot, @AnUnknownMiner! But I will wait for an answer about the server/channel part.

**Comment by bashtech** [comment]
Limit is per connection. 

Also, if you are a mod in a channel and send for example 50 message without getting locked out but send one message to a channel where you are not a mod you will still be locked out since you are over 20.

**Comment by Defman21** [comment]
Thanks, @bashtech!
