### ISSUE TITLE
SSL Support for //www.twitch.tv/CHANNEL_NAME_HERE/embed

### ISSUE THREAD

**Issue by cene-co-za** [justintv/Twitch-API#308]
The community requires SSL support for the twitch embeds to maintain a healthy SSL page state.
Please :)

**Comment by bashtech** [comment]
If you require an embed at supports SSL than I'd recommend looking at the Flash embed described here: https://github.com/justintv/Twitch-API/blob/master/player.md

/embed also provides an HTML5 player which does not support SSL at this time. (Video system would also need to serve video over SSL and that would require a significant expansion of capacity.)

**Comment by cene-co-za** [comment]
Appreciate the quick response. I am aware of the flash embed supporting SSL.
But knowing that there is no concrete deadlines for HTML5 SSL video, at least we can make a plan.
