### ISSUE TITLE
Embedded Twitchplayer broken with VOD's under the new VOD system

### ISSUE THREAD

**Issue by Eksrow** [justintv/Twitch-API#309]
The twitchplayer is appending an 'a' to the archive id you give it in it's parameters, causing it to fail because the new videos have a v as prefix. I assume there are more changes that need to be done under the hood, is there an ETA for this?

**Comment by hallcp** [comment]
Can you please give a concrete example of this behavoir?

**Comment by Eksrow** [comment]
A working example:

Amazhs's channel is still on the old system, thus if we check:

https://api.twitch.tv/kraken/channels/amazhs/videos?broadcasts=true

It'l give us video's with:

"_id": "a614475356"

The twitchplayer accepts:

archive_id: 614475356

You'l see a get request being sent to api.twitch.tv/api/videos/a614475356 by the twitchplayer

Which loads the correct vod.

----------

Now a non-working example.

Sivhd's channel is on the new system

https://api.twitch.tv/kraken/channels/sivhd/videos?broadcasts=true

It'l give us video's with:

"_id": "v3714522"   (Notice the v instead of an a)

The twitchplayer accepts:

archive_id: 3714522

You'l see a get request being sent to api.twitch.tv/api/videos/a3714522 by the twitchplayer but failing. I assume even if it did send a URL to api.twitch.tv/api/videos/v3714522 it would still fail as the new vod system does not use this endpoint anymore but the usher endpoint for m3u8 playlists.

---
archive_id: v3714522

Doesn't work either, the player appends an 'a' to the request it sends.

**Comment by Eksrow** [comment]
I didn't mean to close this, pressed the wrong button

**Comment by hallcp** [comment]
Thanks.  Folks will take a look.

**Comment by night** [comment]
Check out the updated player docs: https://github.com/justintv/Twitch-API/blob/master/embedding.md#videos

**Comment by Eksrow** [comment]
Yep that's it, cheers,
