### ISSUE TITLE
Bug: GET /channels/:channel/follows intermittently excludes unexpected users

### ISSUE THREAD

**Issue by schmich** [justintv/Twitch-API#314]
The [`GET /channels/:channel/follows`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-channelschannelfollows) endpoint appears to return incorrect data a short time after a user follows or unfollows the channel. I believe the nature of the problem is due to eventual consistency coupled with paged responses and inconsistent server routing.

Using a friend's channel ([real_jansoon](http://www.twitch.tv/real_jansoon/profile), 230 followers at the time of testing) while he was not broadcasting, we had his alternate account (`jansoonnsfw`) follow and unfollow his channel. At the same time, I ran the script at the bottom to use the API to snapshot his followers list every 10 seconds and display the changes (users added/removed) from the previous snapshot. The output:

```
{:removed=>[], :added=>[]}
{:removed=>[], :added=>[]}
{:removed=>["timeshadow199"], :added=>[]}
{:removed=>["kyuriin"], :added=>["timeshadow199"]}
{:removed=>[], :added=>[]}
{:removed=>[], :added=>["kyuriin"]}
{:removed=>["jansoonnsfw"], :added=>[]}
{:removed=>["timeshadow199"], :added=>["jansoonnsfw"]}
{:removed=>[], :added=>["timeshadow199"]}
{:removed=>["jansoonnsfw", "timeshadow199"], :added=>[]}
{:removed=>[], :added=>["jansoonnsfw", "timeshadow199"]}
{:removed=>[], :added=>[]}
{:removed=>["kyuriin"], :added=>[]}
{:removed=>["jansoonnsfw"], :added=>["kyuriin"]}
{:removed=>[], :added=>["jansoonnsfw"]}
{:removed=>["timeshadow199"], :added=>[]}
{:removed=>[], :added=>["timeshadow199"]}
{:removed=>[], :added=>[]}
{:removed=>["jansoonnsfw", "timeshadow199"], :added=>[]}
{:removed=>[], :added=>["jansoonnsfw", "timeshadow199"]}
{:removed=>["jansoonnsfw"], :added=>[]}
{:removed=>[], :added=>[]}
{:removed=>["timeshadow199"], :added=>["jansoonnsfw"]}
{:removed=>["jansoonnsfw"], :added=>[]}
{:removed=>[], :added=>["jansoonnsfw", "timeshadow199"]}
{:removed=>["jansoonnsfw"], :added=>[]}
{:removed=>["timeshadow199"], :added=>[]}
{:removed=>[], :added=>[]}
{:removed=>[], :added=>["timeshadow199"]}
{:removed=>[], :added=>[]}
{:removed=>[], :added=>[]}
{:removed=>[], :added=>[]}
{:removed=>[], :added=>[]}
...
```

The API eventually gets to a consistent state (`jansoonnsfw` is added, no other users affected), but  notice that two other users appear and disappear intermittently: `kyuriin` and `timeshadow199` (we verified that they weren't randomly following/unfollowing him during our tests).

As it turns out, `timeshadow199` is follower number 30 `kyuriin` is follower number 130. The script makes requests in batches of 100 from the API by time descending, and my friend has 230 followers total, so `kyuriin` is the last follower in the first request, and `timeshadow199` is the last follower in the second request.

I believe this is because of the following: in order to get all of my friend's followers, we must make 3 requests to the Twitch API. Each request can end up hitting different servers with different caching/consistency, so, the worst-case scenario (assuming requests with `limit=100`) is:

- Our first request routes to a server that knows about `jansoonnsfw`, so `kyuriin` (now follower number 101) gets excluded from the response (which includes followers 1-100).
- Our second request routes to a server that does *not* know about `jansoonnsfw`, so `kyuriin` is follower number 100 and gets excluded from the response (which includes followers 101-200).
- The net effect is that it appears that `kyuriin` is not following `jansoonnsfw`.

Solutions:

1. Workaround: We make multiple requests to Twitch for each batch of followers, and union all of the responses with the expectation that, given enough requests, we will hit servers with different world views, and will *probably* be able to construct the underlying truth.
2. Twitch provides a server token/ID response header that can be used in subsequent requests to ensure they get routed to the same server (e.g. `X-Server-Id: api-server-42`). In this case, we would at least be requesting against an internally-consistent world view.
3. Twitch updates their load balancer to route requests from one IP to the same server and can provide a guarantee that clients will hit the same server as long as their IP doesn't change.

I imagine this is an issue with all other API endpoints that have paged responses.

We're currently trying to create an unfollow notifier, and that depends on having correct data, so it would be nice to get some sort of fix here beyond the hacky solution 1 above.

Thanks & regards,
Chris

```ruby
require 'open-uri'
require 'json'
require 'set'
require 'pp'

def followers(channel)
  url = "https://api.twitch.tv/kraken/channels/#{channel}/follows?limit=100"
  names = Set.new

  while url
    json = JSON.parse(open(url, 'Accept' => 'application/vnd.twitchtv.v3+json').read)
    batch = json['follows'].map { |f| f['user']['name'] }
    break if batch.empty?
    names += batch
    url = json['_links']['next']
  end

  names.map(&:downcase)
end

prev = curr = []

loop do
  prev, curr = curr, followers('real_jansoon')
  pp({ removed: prev - curr, added: curr - prev })
  sleep 10
end
```

**Comment by schmich** [comment]
Thinking about this more, my proposed solutions still fail if users follow/unfollow in between paginated requests, though that's only really a problem if the data set changes frequently.

I imagine the full solution here is to implement cursors [like Twitter has done with their API](https://dev.twitter.com/overview/api/cursoring) along with consistent routing or a strongly consistent data store for the paged result set.

**Comment by Fugiman** [comment]
Specifying `direction=asc` will cause the results to be returned in ascending order, which will fix the issue of follows making it appear as though people have unfollowed you. However, it won't fix the pagination issue in the event of unfollows.

For that case, I'd recommend setting your offset to less than your limit. For example, if you set `limit=100&offset=96`, your script will be able to handle 4 people unfollowing without losing data.

Any solution involving Twitch changing it's routing or caching logic will likely take a very long time to implement, so I hope my advice will let you get your project running without requiring changes on Twitch's end.

**Comment by schmich** [comment]
Thanks for the workaround, it seems workable and more dependable than what I had suggested.

As a parting suggestion, consider dropping a note about this behavior into the API docs. The behavior isn't intuitive, and it took me a bit to realize what was actually going on here. Thanks again!
