### ISSUE TITLE
auto_play=false broken on /v/ highlights

### ISSUE THREAD

**Issue by Lighnat0r** [justintv/Twitch-API#315]
Using the auto_play=false parameter on /v/ highlights does not stop them from playing automatically.
The video starts playing but the controls still look as if it's paused.
isPaused() returns true while it is playing in this manner, though pauseVideo() does pause it.

**Comment by cmillward** [comment]
This is a repeat of a known issue. We'll be tracking it here: https://github.com/justintv/Twitch-API/issues/289
