### ISSUE TITLE
Follow Users -- Token invalid or missing required scope

### ISSUE THREAD

**Issue by JoshW816** [justintv/Twitch-API#322]
Im using the Twitch API to allow users to follow other twitch.tv users from my website. However, every time I make the request to follow a user, I get the error "Token invalid or missing required scope".

Let me go over everything I've done to ensure that i've done everything correctly
1) Ive created my application on Twitch
2) Ive authenticated my application with a specific user including the scope "user_follows_edit", gathering the token and storing it in my database
3) Im using PHP to send a cURL request to the v3 version of the Twitch API. No php errors.

This is the code im using to make the request

        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_CUSTOMREQUEST => 'PUT',
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_CONNECTTIMEOUT => 0,
            CURLOPT_URL => 'https://api.twitch.tv/kraken/users/'.$action_user_name.'/follows/channels/'.$target_user_name,
            CURLOPT_HTTPHEADER => array(
                'Authorization: OAuth ' . $action_user_token,
                'Client-ID: ' . $this->client_id,
                'Accept: application/vnd.twitchtv.v3+json',
                'Content-Length: 0'
            )
        ));

        $resp = curl_exec($curl);
        return $resp;

Return

        {"0":"{\"error\":\"Unauthorized\",\"status\":401,\"message\":\"Token invalid or missing required scope\"}"

The variables used in this request are all valid. I've attempted to use both the v2 and the v3 version of the twitch api. Both return the same error.

**Comment by Fugiman** [comment]
Can you try accessing `https://api.twitch.tv/kraken/` with your oauth token? I'd suspect that you're either trying to use an access code instead of an authorization token, or your token has since become invalid.

Each (user_id, client_id) pair can only have one valid token at a time, so if you've generated another token with your application since the one you put in the database, that'd be the problem.

**Comment by JoshW816** [comment]
You're right, I was using the code instead of the token.

I've fixed the issue.

Thanks!
