### ISSUE TITLE
County streams?

### ISSUE THREAD

**Issue by TheMoonLite** [justintv/Twitch-API#323]
any way filter stream by country. like:

https://api.twitch.tv/kraken/streams?country=us

or some else?

**Comment by bashtech** [comment]
Closest you can get is language:
https://api.twitch.tv/kraken/streams?broadcaster_language=ISO_CODE

Languages: http://help.twitch.tv/customer/portal/articles/1771242

**Comment by TheMoonLite** [comment]
Thank's!
