### ISSUE TITLE
Highlight using sliders inaccurate and buggy.

### ISSUE THREAD

**Issue by edge226** [justintv/Twitch-API#328]
As per #327 I tired using the current time as the in/out point in a lightlight. This failed horribly. Next I tried using the sliders that were on the video frame. Trying to get the time I wanted was frustrating and inaccurate. When the final video was produced it had tacked on frames from the start of the broadcast onto the start of the highlight video. These frames should not have been added.

I think the sliders should also snap onto the current time before times around it to make selecting the point you want easier.

**Comment by Fugiman** [comment]
This tracker is for issues in our API, not with the website itself. To report an issue with our website, please email bugs@twitch.tv
