### ISSUE TITLE
`recorded_at` incorrect

### ISSUE THREAD

**Issue by pencil** [justintv/Twitch-API#331]
It looks like the API is indicating the wrong starting time stamp for multiple VODs. For [this VOD](http://www.twitch.tv/forsenlol/v/3824810) the [API reports](https://api.twitch.tv/kraken/videos/v3824810) that the recording started at 2015-02-23T10:04:47Z. As you can see on the screen (right at the start) however, the time seems to differ:
![image](https://cloud.githubusercontent.com/assets/812086/6373690/8d70d3b0-bd0c-11e4-81a0-d548c024dd3e.png)
Sweden's timezone is UTC+1 so the `recorded_at` should read something like `2015-02-23T17:03:00Z` (assuming that `recorded_at` is still UTC as it used to be).

Another example: For [this VOD](http://www.twitch.tv/rxnexus/v/3824869), [the API says](https://api.twitch.tv/kraken/videos/v3824869) that it's time frame is from "2015-02-23T16:55:33Z" (`recorded_at`) to "2015-02-23T17:18:22Z" (`recorded_at` + `length` seconds). While for [another VOD of the same channel](http://www.twitch.tv/rxnexus/v/3824385) the [reported time frame](https://api.twitch.tv/kraken/videos/v3824385) is "2015-02-23T14:50:12Z" to "2015-02-23T17:16:56Z". As you can see, the reported time frames overlap which doesn't seem plausible.

**Comment by pencil** [comment]
It looks like the timestamp reported in the m3u8 playlist seems to be correct: `#ID3-EQUIV-TDTG:2015-02-23T17:03:53` It's just the API reporting the wrong timestamp.

**Comment by luxflux** [comment]
:+1: Need this too.

**Comment by cmillward** [comment]
Thanks for the heads up; looking into it.

**Comment by pencil** [comment]
Looks like only replay recorded at 2015-02-23 had wrong timestamps. Probably just some random hiccups.
