### ISSUE TITLE
Unlink my application (Logout)

### ISSUE THREAD

**Issue by xbenax** [justintv/Twitch-API#333]
Hi, how can i remove my app of a user account?, i associate my app to a user and use the access token to control the user account but i need "invalidate" this access token if the user clicks in a button "Log Out", how can i do this? (I not need generate other access token, i need remove this)

Thanks

**Comment by xbenax** [comment]
help me please

**Comment by xx-k** [comment]
What exactly is the need for this? Why wouldn't you want you application automatically authorize the user for each subsequent visit/use/etc.?

**Comment by xbenax** [comment]
My application accesses to user data and i believe that users have the right to stop using my app at any time.

**Comment by Fugiman** [comment]
`DELETE https://api.twitch.tv/kraken/oauth2/authorization/CLIENT_ID?oauth_token=OAUTH_TOKEN`

**Comment by xbenax** [comment]
@Fugiman this not work for me, i remplace CLIENT_ID and OAUTH_TOKEN, but server return "{"error":"Not Found","status":404,"message":null}".

The Twitch manual, say this: "you can revoke authorization for an application or website by clicking the "revoke" link on the relevant row.", i need add a revoke button to my web, when the users clicks in the button, my application and your account are unlinked. (this is for security)

**Comment by Myrathi** [comment]
@xbenax Ensure that you're using the DELETE method request and not a GET or a POST.

**Comment by gautam-bst** [comment]
@Fugiman 
I am also getting the similar issue, getting status 400 (Bad Request). I am making the call from angular $http. Can you please suggest or provide the code you used for unlinking the application.

Thanks
Gautam Pahuja
