### ISSUE TITLE
Information at endpoint /users/{user}/follows/channels is not up-to-date.

### ISSUE THREAD

**Issue by xx-k** [justintv/Twitch-API#335]
When browsing to the endpoint found at 

     https://api.twitch.tv/kraken/users/{user}/follows/channels

the information contained about the different channels is not up to date or isn't refreshed properly. This can be seen on e.g. the 'status' (if it is defined) property of each 'channel' objects, as this property differs when checking at the endpoint

     https://api.twitch.tv/kraken/streams/{channel}

or

     https://api.twitch.tv/kraken/streams/?channel={channel1,channel2,...}

to something which seems to be the previous status (e.g. the **/users/{user}/follows/channels** contains the previously set status, compared to the **/streams/{channel}** endpoint)

I'm guessing this isn't intended, as I've only begun experiencing this recently. Should I migrate to extracting the 'status' property from the **/streams/** endpoint instead?

**Comment by martijnhoekstra** [comment]
issue 303 possibly related?
