### ISSUE TITLE
Get channel a user is currently viewing

### ISSUE THREAD

**Issue by aneeven** [justintv/Twitch-API#340]
Is there any way to retrieve if a user is currently watching a stream and if so, which one?

If you've linked your twitch account to steam, they surely have a way to know if you're watching a specific stream (e.g. to drop in-game items for viewers).

**Comment by bashtech** [comment]
I'd personally consider that a privacy violation of you could simply lookup
whatever stream an arbitrary user is currently watching.

If you want all viewers of a channel then your best off to use the tmi
endpoint to get a list of users logged into chat.
