### ISSUE TITLE
[Request] Need Way To Authenticate Without URL Redirect

### ISSUE THREAD

**Issue by GoldenSphere** [justintv/Twitch-API#342]
We are developing an iOS app, and need a way to authenticate a user. The URL redirect method won't work, since there is no server or client URL to redirect to - since the user is running an iOS app.

Instead we need a method to authenticate a user directly within the app.

**Comment by scagood** [comment]
This is me just thinking out loud but could you create either a temporary local server or add a scheme which redirects to your app.

Hope this helps,
scagood

**Comment by Fugiman** [comment]
Please see http://discuss.dev.twitch.tv/t/does-twitch-authentication-api-support-username-password-flow/1871
