### ISSUE TITLE
Redirect URI not called?

### ISSUE THREAD

**Issue by lfdversluis** [justintv/Twitch-API#343]
I've tried both the authentication flow and the implicit grant flow and both of them hang on the following url ``https://api.twitch.tv/kraken/oauth2/allow``. I am not sure why though. I see the login and authenticate screen perfectly, also the application shows up in my settings list on the twitch website, yet I do not get redirected to the URI I've provided. 

Any ideas?

**Comment by scagood** [comment]
Where are you trying to use https://api.twitch.tv/kraken/oauth2/allow with neither "Authorization Code Flow" or "Implicit Grant Flow" use kraken/oauth2/allow.

Authorization Code Flow uses:
  https://api.twitch.tv/kraken/oauth2/
  https://api.twitch.tv/kraken/oauth2/token

Implicit Grant Flow uses:
  https://api.twitch.tv/kraken/oauth2/authorize

if you go to https://api.twitch.tv/kraken/oauth2/allow you'll see it returns a 404 error (even with a auth token with all scopes) 

I would recommend you re go over authentication.md to confirm your auth method 

Hope this helps,
scagood

**Comment by lfdversluis** [comment]
This is being done by twitch after I press the authorize button. I followed the detail exactly as described by [the authenticaion.md](https://github.com/justintv/Twitch-API/blob/master/authentication.md) file.

**Comment by scagood** [comment]
Which method are you using Code Flow or Grant Flow?

Also I want to what you mean what is your auth link?
eg. https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=f03diai4g1nzfwo3om1s87jvdq65hax&redirect_uri=http%3A%2F%2Fauth.scagood.co.uk%2F&scope=user_read

**Comment by lfdversluis** [comment]
I've tried both actually. My current code is set to Code Flow. The link is like this: 

``"https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=" + clientid + "&redirect_uri=" + callback + "&scope=" +
            "user_read+" + "user_blocks_edit" + ...``

**Comment by lfdversluis** [comment]
Might be useful to note I am creating an app, so I first tried the Grant Flow, but since that didn't work I tried the code flow to see if that did work (just sending a POST request extra in that case).

**Comment by scagood** [comment]
Are you redirected to https://api.twitch.tv/kraken/oauth2/allow?code=[CODE] or just to https://api.twitch.tv/kraken/oauth2/allow.
I am assuming that this is immediately after you clicked authorise?

**Comment by lfdversluis** [comment]
With the implicit grant flow, I am not redirected to the URI with the access_token. For the code flow, I am not redirected to the link with the code as get param. So it's just like you say, just to https://api.twitch.tv/kraken/oauth2/allow.

**Comment by lfdversluis** [comment]
Here is a full trace:

``` https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=lnaauyq77oxdemn60ehv3eiiwzkqzjl&redirect_uri=http://laureif80.eighty.axc.nl/mytwitchchannel&scope=user_read
https://api.twitch.tv/crossdomain/receiver.html?v=2
https://www.google.com/recaptcha/api/challenge?k=6LfBFwMTAAAAANPSl1qMQV02JSmETF0e12nXFJ3d&ajax=1&cachestop=0.5180448582395911
https://api.mixpanel.com/track/?data={cut because of long line spam}
https://www.google.com/recaptcha/api/image?c=03AHJ_VuuZksYgWG0ivt5sQiBoGg9HvVtfMKG4ZdTn5wRmkDwDyWCN0vCi3lED3EJmznPf4JrcVdMj0FLyFtYvlRAuq2Ku-cJ9HUBRrBGvAFUzs1Z2PyGb0yYRnXzcKsezyRMj334bppRCXWPuuXENXOvO37Y_BXXHYfbAxkCL9u74_T-G2OHXqKjHwoNQbdtAUFan3N_YDUSh
 HERE I LOG IN
https://api.twitch.tv/kraken/oauth2/login
 HERE I SEE THE WANT TO AUTHORIZE SCREEN?
http://static-cdn.jtvnw.net/jtv_user_pictures/cookieandegg-profile_image-04f1f4c19fcc3e1f-150x150.jpeg
https://api.mixpanel.com/track/?data={cut because of line line spam}
HERE I PRESS AUTHORIZE
https://api.twitch.tv/kraken/oauth2/allow
```

**Comment by scagood** [comment]
JS Code Flow (This should not work...)
```javascript
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
var twitchAuthUri = "https://api.twitch.tv/kraken/oauth2/";
var clientId = "f03diai4g1nzfwo3om1s87jvdq65hax";
var clientSecret = ""; // Removed...
var clientUri = "http://auth.scagood.co.uk/";

function getUrlParam(paramName) {
    // Search for param in url
    var nameRegex = new RegExp("[?#&]"+paramName+"=([^&#]+)").exec(window.location.href);
    // If there is a value return it
    if (nameRegex != null)
        return  nameRegex[1] || 0;
    
    return false;
}

window.onload = function() {
    if (getUrlParam("code") != false) {
        // Get the code
        var code = getUrlParam("code");

        // Send the post reqest
        $.ajax({
            type: "POST",
            url: twitchAuthUri+"token",
            crossDomain: true,
            // Build the post request data
            data: 'grant_type=authorization_code&client_id='+clientId+'&client_secret='+clientSecret+'&redirect_uri='+clientUri+'&code='+code,
            success: function (data) {
                // Decode the returned data
                var returned = JSON.parse(data);
                
                // All you need
                var access_token = returned.access_token;
                var scope = returned.scope;
                
                console.log("Token: "+access_token, ", Scope: "+scope);
            }
        });

    }

    // This just redirects to the auth page if the scope param is present without the code param
    else if (getUrlParam("scope") != false) {
        builtUrl = twitchAuthUri + "authorize";
        builtUrl = builtUrl + "?response_type=code";
        builtUrl = builtUrl + "&client_id=" + clientId;
        builtUrl = builtUrl + "&redirect_uri=" + clientUri;
        builtUrl = builtUrl + "&scope=" + getUrlParam("scope");
        
        window.location.href = builtUrl;
    }
}
</script>
```

JS Grant Flow (This worked for me)
```javascript
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
var twitchAuthUri = "https://api.twitch.tv/kraken/oauth2/";
var clientId = "f03diai4g1nzfwo3om1s87jvdq65hax";
var clientUri = "http://auth.scagood.co.uk/";

function getUrlParam(paramName) {
    // Search for param in url
    var nameRegex = new RegExp("[?#&]"+paramName+"=([^&#]+)").exec(window.location.href);
    // If there is a value return it
    if (nameRegex != null)
        return  nameRegex[1] || 0;
    
    return false;
}

window.onload = function() {
    if (getUrlParam("access_token") != false) {
        // Get the access token and scope
        var access_token = getUrlParam("access_token");
        var scope = getUrlParam("scope");
        
        console.log("Token: "+access_token, ", Scope: "+scope);
        
    } else 
        if (getUrlParam("scope") != false) {
            // This just redirects to the auth page
            builtUrl = twitchAuthUri + "authorize";
            builtUrl = builtUrl + "?response_type=token";
            builtUrl = builtUrl + "&client_id=" + clientId;
            builtUrl = builtUrl + "&redirect_uri=" + clientUri;
            builtUrl = builtUrl + "&scope=" + getUrlParam("scope");
            
            window.location.href = builtUrl;
        }
}
</script>
```

I am assuming you are using JS from the fact that it's an app

If I am on the wrong lines please tell me :stuck_out_tongue_winking_eye:

My settings are as follows:

![untitled](https://cloud.githubusercontent.com/assets/2230835/6762223/1466b106-cf54-11e4-970f-241e14fe2e5d.png)

Hope this helped (If anything is wrong please say as I just threw it together :smile:)
scagood

**Comment by lfdversluis** [comment]
Sorry @scagood it's actually 100% Java (android app). The code itself is very similar, so I am not sure what goes wrong.

**Comment by lfdversluis** [comment]
Tried to use a subdomain like you do, even this small example fails:

```
final static String clientid = "lnaauyq77oxdemn60ehv3eiiwzkqzjl";
final static String callback = "http://auth.laureif80.eighty.axc.nl/";
final static String callaccess = "https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=" + clientid + "&redirect_uri=" + callback + "&scope=" + "user_read";

...

public void getOauthToken(){

	webview = (WebView) findViewById(R.id.webview);
	webview.getSettings().setJavaScriptEnabled(true);
	webview.loadUrl(callaccess);

	webview.setWebViewClient(new WebViewClient() {
		@Override
		public void onLoadResource(WebView view, String url) {
			Log.e("TwitchOAuth URL", url);
			Uri uri= Uri.parse(url);
			if (uri.getQueryParameter("access_token") != null) {
				final String accesscode = uri.getQueryParameter("access_token");
				Log.e("TwitchOauth token", accesscode);
			}
			else {
				super.onLoadResource(view, url);
			}
		}
	});
}
```

**Comment by scagood** [comment]
You might want to use:
```
void onPageFinished(WebView view, String url)
Notify the host application that a page has finished loading.
```

Instead of checking every resource the page calls.

Also you should consider url encoding the callback url
```
callback = URLEncoder.encode(callback);
```

After doing that you should get a trace like:
```
https://api.twitch.tv/kraken/oauth2/authenticate?action=authorize&client_id=lnaauyq77oxdemn60ehv3eiiwzkqzjl&redirect_uri=http%3A%2F%2Flaureif80.eighty.axc.nl%2F&response_type=token&scope=user_read
--- Logged In ---
https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=lnaauyq77oxdemn60ehv3eiiwzkqzjl&redirect_uri=http%3A%2F%2Flaureif80.eighty.axc.nl%2F&scope=user_read
--- Pressed Authorise ---
http://auth.laureif80.eighty.axc.nl/#access_token=[some random token]&scope=user_read
```

I don't know Java just have to make that clear :smile:
If that does not work or help then it is 100% above me :disappointed:

Hope this helps,
scagood

**Comment by lfdversluis** [comment]
No as I said I went and made some changes, tried a few things here and there. So It might got inconsistent with previous posts. But I'll try your idea. I'll come back to it ^^

**Comment by lfdversluis** [comment]
@scagood Apparently you are more of an Java programmer than I am, haha. The ``onPageFinished`` idea was great. Apparently the last url doesn't trigger when loading a resource. Thanks a lot pal, you really helped me out here.
