### ISSUE TITLE
Fake Twitch account

### ISSUE THREAD

**Issue by rbozan** [justintv/Twitch-API#344]
Is there a possibility to create a fake Twitch account? So we can add fake random followers (give ourself 50000 followers as example), fake livestreams (make the channel go 'live' without showing content), fake videos (random videos that we 'uploaded'), so we can test if our apis are working correctly.

**Comment by scagood** [comment]
I don't think that would be allowed. The way I tested my bot is by going out and asking streamers whether I could test it in their streams :smiley_cat: (only 1 person said no). As their channels build I could start to see the flaws appearing in my bot which I fixed as and when it was needed.

**Comment by belthesar** [comment]
What you're looking for is a sandbox, which I don't believe Twitch has.

**Comment by youssefdetovernickr** [comment]
i cri evertiem

**Comment by N0zz** [comment]
Basically most of the data in twitch api is public and free to use. And if something is not, you have to get authorized app connected to specific account to get this. So, you can test it on any account on twitch and there wouldn't be any problem with that. So, why do you need sandbox with fake accounts, when you can use milions of real accounts created and used by other users?

**Comment by TournyMasterBotCurse** [comment]
@N0zz Because sometimes it's better to test in a sandbox to establish how things work instead of creating data people 'in the wild' might stumble across and thing is real. Sandboxes are typically also sanctioned away from prod, so if you accidentally break something in a bad way, you don't break a production site.

**Comment by N0zz** [comment]
@TournyMasterBotCurse Well, thats true, but... Its just an API. What can you break in there? Most of API using here is just "get". There are few things that you can edit. And in worst case scenario you just will generate new stream key for your account or something like that. Its not like dropping production database with important data etc...

**Comment by scagood** [comment]
I think it is more for testing partner functions e.g. getting subscribers and testing it. I personally would not like to jump into the deep end on a big channel and then muck up... So it is less about breaking something and more about making sure everything runs smoothly before you 'jump'.

This is just my personal opinion :smile:

Thanks 
scagood

**Comment by TournyMasterBotCurse** [comment]
@scagood  That's pretty much what I was getting at - thanks for clarifying it :)

**Comment by N0zz** [comment]
Well, I have nothing more to say in this topic. You guys are right and thankfully you did explained to me why is that more important that I thought :)

**Comment by TournyMasterBotCurse** [comment]
@DallasNChains There is still a big interest in getting a twitch sandbox, especially for things to replicate partner features for testing. Is there an official topic for a sandbox?

**Comment by DallasNChains** [comment]
There isn't an official topic for a sandbox. Feel free to start a thread in the forums though! A sandbox is less about the API and more about developer infrastructure, which is why I closed this. :)
