### ISSUE TITLE
Chat API

### ISSUE THREAD

**Issue by addemod** [justintv/Twitch-API#345]
Is there some way to send a kind of notice with the current API?
Like when a user gets timed out, only that user get a notice that only he sees.

**Comment by bashtech** [comment]
Not currently.

**Comment by belthesar** [comment]
@addemod That notice is sent via TMI in the chat to the user, and there's code to handle that in the chat widget to make that appear as such.  Those notices are sent by the server, and we don't have any exposure to TMI to make those kinds of notices.

**Comment by FineNerds** [comment]
You could have a command that you tell a bot so that everyone knows. The bot could then echo a preset message saying that person was muted.
