### ISSUE TITLE
Get time when stream started

### ISSUE THREAD

**Issue by mcrozz** [justintv/Twitch-API#346]
Is there any way to get a time when stream get started?

Right now on stream endpoint you can get only time of changing stream's title.
> https://api.twitch.tv/kraken/streams/:USER

Thanks in advance!

**Comment by Fugiman** [comment]
https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel

The "created_at" field tells you when the stream started.
