### ISSUE TITLE
Getting views of channel instead of concurrent viewers

### ISSUE THREAD

**Issue by Ghostru** [justintv/Twitch-API#348]
Via https://api.twitch.tv/kraken/channels/ I started to get in views number of all channel views instead of concurrent viewers...

**Comment by bashtech** [comment]
Your probably thing about `/streams/:channel` which has concurrent viewers. Since a channel isn't always live having concurrent viewers on that endpoint doesn't make much sense.

**Comment by scagood** [comment]
https://api.twitch.tv/kraken/streams/[channel] 
if they are not streaming stream will be null
->stream->viewers

shown here: https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel

**Comment by Ghostru** [comment]
thanks a lot!
