### ISSUE TITLE
Expose the user's chat color in the API

### ISSUE THREAD

**Issue by AuroraAri** [justintv/Twitch-API#362]
This'd be really helpful in a website I'm developing!

**Comment by Fugiman** [comment]
We expose it through chat whenever a user sends a message. How is it useful outside of the context of chat?

**Comment by AuroraAri** [comment]
For example, on speedrun.com and hpspeedruns.com, the site allows users to select a color that is displayed whenever the username is displayed. Being able to get the user's chat color from Twitch would help with the setup of new user accounts on sites that want to use a similar system. :)

Ideally, it'd be exposed as an RGB code, like ("display_color": "#FF0000";)

**Comment by AnUnknownMiner** [comment]
Exposing the user's color in chat could be used in applications that use a console, such as user-side bots or minecraft (bukkit) plugin that allow a streamer to see twitch chat without having to have multiple windows open.

**Comment by bashtech** [comment]
If you are connected to IRC already to display the chat then you have
access to the user colors directly through v3 tags.

**Comment by AuroraAri** [comment]
That's true, but having access to it as a separate element would be useful in its own right.

**Comment by Fire-** [comment]
My opinion is that a user's chat color serves no real purpose outside of our own chat as the color choices users make are based on our site's color scheme. They should not be assumed to match on any other site or color scheme, and ideally should not be bound together for that reason. It's a chat-specific property, not a general user property.
