### ISSUE TITLE
Embedding streams via HTTPS

### ISSUE THREAD

**Issue by arnarthor** [justintv/Twitch-API#374]
Your embedding solution given on twitch.tv using iframe does not support https traffic. 
Is there any way (preferably not using flash) that allows me to embed streams using https?

Currently my code looks like this

```js
      <iframe
        className="TwitchAttachment__video"
        type="text/html"
        width="530"
        height="298"
        scrolling="no"
        src="http://www.twitch.tv/scarra/embed"
        frameBorder="0"
        allowFullScreen
      />
```

When changing `http://` -> `https://` the embed does not load.

**Comment by bashtech** [comment]
Not at this time.

**Comment by jeremyhaile** [comment]
+1

**Comment by dreamcation** [comment]
+1

**Comment by johnRivs** [comment]
+1

**Comment by dylannz** [comment]
:+1:

There appears to be a solution (although it's pretty hacky) in the link you posted, but it does work which is better than the current behaviour.

YouTube plays nicely with HTTPS, I don't know why Twitch can't :/

**Comment by Fugiman** [comment]
Should have been fixed when the entire site moved to HTTPS, but you still need Flash
