### ISSUE TITLE
how to get user?

### ISSUE THREAD

**Issue by mjacksoning8** [justintv/Twitch-API#378]
how can i do get user?

Hi, i got token and i need do this request "https://api.twitch.tv/kraken/users/test_user1 ".

How i can do it? im using gwt ( java )

**Comment by scagood** [comment]
What are you trying to ask?
This is the Twitch api issues tracker so if you are looking for help please search http://discuss.dev.twitch.tv/c/api or possibly ask on there for help

Thanks scagood

**Comment by mjacksoning8** [comment]
Here is all the information 
https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser
but i dont understand how i can do the request.
i am working in GWT ( java )
Date: Sat, 2 May 2015 15:05:37 -0700
