### ISSUE TITLE
Stream Key Reset - Token invalid or missing required scope

### ISSUE THREAD

**Issue by Juangb92** [justintv/Twitch-API#379]
I'm using the Twitch API to reset the stream key for a user using PHP. I've succesfully retrieved the stream key using the OAuth token. But when I try to make a DELETE request I get an Unauthorized error:
```
{"error":"Unauthorized","status":401,"message":"Token invalid or missing required scope"}
```
I've tried setting the authorization token in the URL ...
```
$url="https://api.twitch.tv/kraken/channels/(channel's name)/stream_key?oauth_token=$accessToken";
```
...and as a Header but I still get the message. 

This is my code:
```
$url="https://api.twitch.tv/kraken/channels/(channel's name)/stream_key";
$accept = "Accept: application/vnd.twitchtv.v3+json";
$authorization = "Authorization: OAuth $accessToken";
$ch = curl_init();

curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
curl_setopt($ch,CURLOPT_HTTPHEADER , array($accept, $authorization));
 
$output=curl_exec($ch);
if($output === false)
{    echo 'Curl-Error: ' . curl_error($ch);}
else
{   echo $output;
	$json_a=json_decode($output,true);
	echo "STREAM_KEY: " . $json_a['stream_key'];
 }
 
curl_close($ch); 
```

I'm pretty sure I'm using the correct token since, as I mentioned, I was able to get my stream key by getting the channel's object. Also, I'm sure that I'm using the correct scopes (for now: "channel_read" and "channel_stream").

Do you have any idea of what could be the problem?

**Comment by scagood** [comment]
You may want to check the scopes here: https://api.twitch.tv/kraken/?oauth_token=$accessToken as I have a feeling that there is something wrong with oauth tokens at the moment.

The reason I say this is because even though I have deleted access to my twitch account from my dev app the old access tokens still work. aswell as that every time I authenticate a new key with a set of scopes only user_read seems to stay active

Thanks,
scagood

**Comment by scagood** [comment]
I found the auth key of the account I run my bot off of that has all scopes and found that the following works:

```php
<?php
function sendGet($url, $data) {
    $url = $url."?".http_build_query($data);
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_TCP_NODELAY, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $return = curl_exec($ch);
    curl_close($ch);
    
    return $return;
}

$url="https://api.twitch.tv/kraken/channels/$channel/stream_key";
$data = array(
    "oauth_token" => $accessToken,
    "_method" => "DELETE"
);

$output = sendGet($url, $data);
$output = json_decode($output,true);
if (isset($output["stream_key"]))
    echo "Stream Key: " . $output["stream_key"] . "\n";
else if (isset($output["error"]))
    echo "Error: " . $output["error"] . "\n";
else
    echo "I have no idea what happened!\n";
?>
```

**Comment by Juangb92** [comment]
Hi @scagood!

Thank you a lot for your help!

As you said, I checked my scopes at https://api.twitch.tv/kraken/?oauth_token=(access_token) and indeed only the scope for "channel_read" was there and not the "channel_stream" scope that I need. Thing that I find kind of odd since I made the authorization for both of the scopes with the twitch account.

It would be logical at the beginning since I used the first scope but then applied the second one, but apparently it's not applied.

How can I get the proper token for the scopes?

Cheers

**Comment by scagood** [comment]
You should get a new auth token generated for you with the new scope included

Hope this helps,
scagood

**Comment by Juangb92** [comment]
Hi!

Yes, that's exactly what I thought but it doesn't seem to work. This is what I do:

1- Request the authorization code, looks something like this:

https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=(client_id)&redirect_uri=(url)&scope=channel_read+channel_stream

2- I authorize with the twitch user account.

3- I get the code, and using the client id and client secret I request the access token.

4- I get a response like this:
```
{"access_token":"(acces_token)",
"refresh_token":"(refresh_token)",
"scope":["channel_read","channel_stream"]}
```
At this point it seems that the authorization token is related to both of my scopes.

5- I send the token using with the PHP code that I wrote in the first comment.

Technically, and as far as I understand that token should work. But every time that I check the kraken url that you mentioned with my token it only shows the first scope (channel_read). Causing the Unauthorized error.

Every time I access my page the token is updated.
Maybe I'm not using the right token? 

Thank you again. :)

**Comment by scagood** [comment]
You could try changing browsers as I am having a problem like that (in chrome) but I changed browsers (to firefox) and it works again sort of...

Also your code works perfectly for me using a key with the channel_stream scope.

Thanks scagood

**Comment by Juangb92** [comment]
Changing the browser didn't actually work, the scopes didn't change even after removing all rights and assigning only the channel_stream scope.

However, I used another app with a different client_id and a different client_secret (registered by another twitch user) and at the end I could set the correct scope. 

It's like if I couldn't allow the use of an app registered by the same twitch user account. I don't know if this is supposed to be normal. I have two accounts, one with the app registered and another one for testing the app. At least I have it working now. :) 

Thank you again.
Juangb92
