### ISSUE TITLE
Dutch translate issue

### ISSUE THREAD

**Issue by Pigzor** [justintv/Twitch-API#381]
This is only a small issue but it has been bothering me for a while. 
When a streamer is playing a game there will be some text saying: "streamer is playing game". 
In Dutch this should be: "streamer speelt game" but now it's showing "streamer wordt afgespeelt game" which is kind of a wrong translation.

Thank's if you guys could fix this :)
Lord_pigzor

**Comment by MrMdemiC** [comment]
Maby an idea that the community can translate for twitch?

maby this is already availible but i could not find it anyware.

**Comment by mjperrone** [comment]
@Pigzor thank you for pointing that out. We'll get that info back to our translators.

@MrMdemiC that's actually something that we used to do a while ago. The results were basically full of Kappas, so we moved away from that.
