### ISSUE TITLE
MOD TOOLS ON MOBILE?

### ISSUE THREAD

**Issue by TheGuyOfLame** [justintv/Twitch-API#384]
Where are the mod tools on mobile?! Some mods can't do anything when someone's advertising on the channel or spamming! It'd be really appreciated to add them.

**Comment by Izlsnizzt** [comment]
Though this isn't API related, mod tools are available on most mobile clients AFAIK, if you tap a name you should have an option to timeout or ban that user (assuming mod status), also normal chat commands such as /timeout or /ban work normally by replacing the / with . so .timeout or .ban

Hope this helps.
