### ISSUE TITLE
Embedding widgets to link to charity fundraising pages on JustGiving

### ISSUE THREAD

**Issue by jamieparkins** [justintv/Twitch-API#386]
Hi,

We are seeing a great number of your gamers running charity gaming sessions and marathons. Quite often JustGiving is used as the fundraising platform of choice (see example at https://www.justgiving.com/MotorNeuronL33tness). At present most people simply seem to link to their JustGiving page but we'd like to help make it easier for users. And so...

1. We can see you can mark up your own widget but are there are APIs that allow - say a widget - to be PUT to a given stream page?

2. Is there a popular widget/embedding service that streamers use for such service? Anyone we should be talking to?

Thanks
Jamie

**Comment by scagood** [comment]
Here is the correct place to ask this type of question. 
Just giving has an api: https://api.justgiving.com/
If you have a feature suggestion I would start here: http://discuss.dev.twitch.tv/ 

With your suggestion I would recommend giving ideas on how it could be implemented e.g. a donation pane above twitch chat or a way of putting forms into the panels sections of pages.

Hope this helps
scagood

**Comment by jamieparkins** [comment]
Thanks - have done so. 

All the best
