### ISSUE TITLE
Follows API returns incorrect timestamps

### ISSUE THREAD

**Issue by DeezjaVu** [justintv/Twitch-API#390]
https://api.twitch.tv/kraken/channels/:channel/follows
The list of returned objects does not contain the correct timestamp (created_at is off by 5 hours).

FIX ASAP plz.

**Comment by scagood** [comment]
I've been seeing the same problem with banning users and creating keys were you do something then immediately check it and it said it was done 7hours ago

This may just be a time zone problem and hence I have been ignoring it :smile:

**Comment by DeezjaVu** [comment]
It is a timezone problem, which for certain things may not matter, but for things such as notifiers, this is huge. Basically this breaks notifiers that make use of (and 100% rely on) the timestamp.

**Comment by amclay** [comment]
This is now fixed.
