### ISSUE TITLE
URI scheme for VODs? (Android)

### ISSUE THREAD

**Issue by lfdversluis** [justintv/Twitch-API#391]
With the release of VODs, is there an URI scheme to open the Twitch app on a VOD? Nothing is documented (yet) in https://github.com/justintv/Twitch-API/wiki/Android-URI-Scheme

**Comment by froueint** [comment]
https://github.com/justintv/Twitch-API/blob/master/mobile_deeplinks.md

**Comment by lfdversluis** [comment]
@froueint Thanks a lot, bud!
