### ISSUE TITLE
GET /streams/summary doesn't work correctly with 'game' param

### ISSUE THREAD

**Issue by cgwic** [justintv/Twitch-API#396]
Simple example:
```
get http://api.twitch.tv/kraken/streams/summary?game=Heroes+of+the+storm
```
returns:
```javascript
{
    "channels": 1,
    "viewers": 3,
    "_links": {
        "self": "https://api.twitch.tv/kraken/streams/summary?game=Heroes+of+the+storm"
    }
}
```

**Comment by MrBeardy** [comment]
The parameter is case sensitive. i.e. `minecraft` and `Minecraft` aren't the same and return different results..

I think the results you're expecting are for `Heroes+of+the+Storm`

**Comment by cgwic** [comment]
You absolutely right, thank you)
I think there's no need to implement case-insensitive request when I can get the name, that API expects from seracrh request as:
```
get https://api.twitch.tv/kraken/search/games?q=Heroes+of+the+storm&type=suggest
```
Thank you for help)

**Comment by MrBeardy** [comment]
Ah, I didn't know about the suggest feature for `/games`. That's pretty neat.
