### ISSUE TITLE
List of games on Twitch

### ISSUE THREAD

**Issue by aneeven** [justintv/Twitch-API#401]
Hey everyone, 

Twitch must be keeping a pretty long list in their database containing all games that can be played on Twitch for the broadcasters and viewers to choose from. Is it publicly available or does anyone have a good resource?

Thanks in advance!

**Comment by cgwic** [comment]
I think almost every game from GiantBomb can be broadcasted on Twitch.
So you can use GianBomb's api to retrieve them.
Also Twitch has giantbomb_id in games json.
