### ISSUE TITLE
Client ID

### ISSUE THREAD

**Issue by NicolasSiver** [justintv/Twitch-API#407]
Hi guys,

Could you add route to the API, to check if [Client ID](https://github.com/justintv/Twitch-API/tree/6566233a58412174713e90959c93c3151e4e0a8f#rate-limits) is valid?

**Comment by TournyMasterBotCurse** [comment]
Why would they do that, other than to support brute forcing client ids (Even though it's public information)? You can check your client id for your application under your connections page for your application.

**Comment by 099io** [comment]
Surely you would make sure that you are using the correct Client ID before event attempting to make an application? As @TournyMasterBotCurse mentioned, if you are really unsure of what it is, for whatever reason, you can just check it under your connections page.

I personally don't see why a way to check it through the API would be required.

**Comment by DallasNChains** [comment]
There is a way to check this now, BTW. Since we're requiring Client-ID on August 8th, we have added the `identified` field to the base /kraken/ endpoint. See the [FAQ for Client-ID](https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108) for more info.
