### ISSUE TITLE
Embeding HTML5 player along with flash

### ISSUE THREAD

**Issue by Lyca0n** [justintv/Twitch-API#409]
I'd like to have the flash player by default but  switch to HTML5 whenever a Mobile device is detected, I know how to do the switch, but how do I embed the HTML5 player

**Comment by hallcp** [comment]
We do not currently have an embeddable, cross-browser HTML5 player, sorry.

**Comment by Fugiman** [comment]
You CAN use an iframe to embed `http://www.twitch.tv/CHANNEL/embed`, which will handle the HTML5 transition for you (if possible), and will be forward compatible with new player releases.
