### ISSUE TITLE
Chat mods != IRC Operators?

### ISSUE THREAD

**Issue by tyrope** [justintv/Twitch-API#410]
I'm running a bot for my own channel and a channel I used to mod for. It used to be fine to check for IRC Operator status to mod-limit a command, which, using the framework it's using, is really simple.

Has this been deprecated? If so, can somebody point me to the part of the API that shows the new method? (and can somebody also explain *why* this has been deprecated, because it seems kind of silly to move further away from [the RFC you're claiming to try to follow](http://tools.ietf.org/html/rfc1459.html).)

The test case:
* I join chat using the browser
* bot connects using oauth key
* wait for event 001
* send `CAP REQ :twitch.tv/membership`
* wait for ~15 minutes to ensure all buffers have been sent.
* I send a debug command to list all users in the channel.
* bot responds with `{Identifier('lozneo'): 0, Identifier('havok840'): 0, Identifier('sirwedgie'): 0, Identifier('jessyquil'): 0, Identifier('seriouslybot'): 4, Identifier('prolurking1'): 0, Identifier('moobot'): 4, Identifier('tehmorag'): 0}` where 0 indicates regular user, 4 an IRC channel operator.

However, both jessyquil and sirwedgie are a mod in that channel. Why is moobot (and itself) 4, but the other mods are 0? In fact, that list is lacking many people, including myself! Surely these JOINs and PARTs are not buffered for over fifteen minutes?

**Comment by TournyMasterBotCurse** [comment]
If you need mods, use /mods

**Comment by bashtech** [comment]
Ideally you should request the tags capability and use user-type instead.

**Comment by Izlsnizzt** [comment]
Or request CAP REQ :twitch.tv/tags and parse user-type in

**Comment by Izlsnizzt** [comment]
Damn George too fast...

**Comment by tyrope** [comment]
Thanks for the quick comments, guys. Since I'd rather not rewrite the entire privilege system from the framework I'm using. Would I need to use /mods in addition to, or in replacement of /membership?

**Comment by bashtech** [comment]
If you want the most reliable privilege system then you really should take
the time to move over to tags.
