### ISSUE TITLE
IRC nick list

### ISSUE THREAD

**Issue by reactormonk** [justintv/Twitch-API#412]
Is there a way to reenable the nick list in IRC? The server doesn't seem to send the nicklist anymore.

**Comment by Izlsnizzt** [comment]
I suggest [this](https://blog.bashtech.net/requesting-user-lists-on-twitch-irc/) article by @bashtech

**Comment by Ollee** [comment]
I'm fairly certain it was disabled during E3 and functionality has yet to
be restored.

-ollee

**Comment by Izlsnizzt** [comment]
It has been restored you just need to request the capability as shown in the article I linked above.

**Comment by reactormonk** [comment]
I've just tried

     /quote cap req :twitch.tv/membership

in weechat, got

     Invalid CAP command

back.

**Comment by Izlsnizzt** [comment]
You need to send it as a RAW command in IRC.

**Comment by reactormonk** [comment]
That's the raw command of weechat. And the problem was that it needs to be caps, `CAP REQ` worked.
