### ISSUE TITLE
Clicking/Channel bugg

### ISSUE THREAD

**Issue by xSuper1** [justintv/Twitch-API#413]
Hi,

if i am clicking on any Channel i dosent work. and if i am going on CS:GO Stream its not loading Streaming - Channels: http://gyazo.com/1c3fd4da2b241ccee17f69184c01d782

i have try it on differnet PC's some times it dosent works.

hope u will fixing it soon...

**Comment by dylanlive** [comment]
The CS:GO directory issue should be resolved.
