### ISSUE TITLE
Fetching user logo when using oauth to authenticate?

### ISSUE THREAD

**Issue by serversides** [justintv/Twitch-API#418]
I am sending the scopes user_read and channel_subscriptions, what do I need to do to retrieve the user's logo?

I know there is the public api which can fetch logo without auth but Id rather not mash the 2 together.

**Comment by bashtech** [comment]
Looks like both `GET /users/:user` (public) and `GET /user` (authenticated) have it.

Ref: https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser

**Comment by serversides** [comment]
Ah thankyou :)
