### ISSUE TITLE
What is the tag_list attribute on a video?

### ISSUE THREAD

**Issue by adampope** [justintv/Twitch-API#425]
A video returns an attribute called `tag_list` in it's response

https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-videosid

I can't find any documentation on what it is or any examples of the data that would be returned.  Is it in use, or does it always return an empty string?

**Comment by bashtech** [comment]
When you create a highlight there is an option to add a comma separated list of tags.

Ex: https://api.twitch.tv/kraken/videos/c4921283

**Comment by adampope** [comment]
Perfect, thanks very much!

**Comment by BrianSipple** [comment]
This answer still seems a bit ambiguous. 

@bashtech by "comma separated list of tags", do you mean `["tag1", "tag2", "tag3"]`, or `"tag1, tag2, tag3"`?

**Comment by bashtech** [comment]
The latter. 

New example: https://api.twitch.tv/kraken/videos/v92483945
