### ISSUE TITLE
API and mobile support 

### ISSUE THREAD

**Issue by castrogstar** [justintv/Twitch-API#426]
Hi,

I've recently paid a developer to customize a twitch extension for my joomla site but when the extension is loaded on mobile, the player shows a missing plug-in warning. I've seen that on twitch.com you can view streams without visiting a mobile site, or needing the app. I've also seen some WordPress extensions that are also able to display streams on a mobile device.

Can someone please assist me with this?

Thanks.

**Comment by appleseedexm** [comment]
He probably just embedded the flash player, which will not work on most mobile devices.
This hardly seems to be an API issue - however, nothing granted, you can contact me on Twitter, see my profile (if you dont have twitter, use the contact form on the website I've linked on twitter), then I can have a look at it.
