### ISSUE TITLE
Return URL to subscriber badge in API

### ISSUE THREAD

**Issue by AuroraAri** [justintv/Twitch-API#428]
I'm not entirely sure how to get a partner's subscriber badge through the API; maybe it should be returned through the channel endpoint?

**Comment by Muddr** [comment]
https://github.com/justintv/Twitch-API/blob/master/v3_resources/chat.md#get-chatchannelbadges

**Comment by AuroraAri** [comment]
Fair enough! Wasn't where I expected to look, but it does make sense. Gracias!
