### ISSUE TITLE
Set embed volume via the Javascript API?

### ISSUE THREAD

**Issue by BradDodi** [justintv/Twitch-API#429]
Hey,

Is there any way to set the volume of the embedded player using the Javascript API? (https://github.com/justintv/Twitch-API/blob/master/player.md)

It appears that you're able to mute/unmute the stream but there's no documentation on setting the volume after the stream has loaded. I'm wondering if there's a method to do so that just isn't documented (such as the 'setQuality' method).

Thanks.

**Comment by scien** [comment]
+1

**Comment by SJAnderson** [comment]
+1

**Comment by jasongornall** [comment]
+1

**Comment by Argus9** [comment]
+1! This is currently only possible by changing iframe srcs.
