### ISSUE TITLE
 search/stream returning 0 results?

### ISSUE THREAD

**Issue by PyroPope** [justintv/Twitch-API#430]
I have had a site that has been using search/stream and that functionality has stopped working as of sometime last night / this morning.

This is returning 0 results:
https://api.twitch.tv/kraken/search/streams?q=starcraft

This works:
https://api.twitch.tv/kraken/search/channels?q=starcraft
So does this:
https://api.twitch.tv/kraken/search/games?q=starcraft

The reason the stream one is important to me, is I want to be able to search by stream title instead of just using the games or username. Channels can search by title, but it does not discriminate between offline or online.

Anyone else having this issue, or does anyone else know the reason for it?

**Comment by dylanlive** [comment]
I'm seeing similar results. Looking into it...

**Comment by alanebro82** [comment]
Indeed.  My DLNA server stopped working due to this.

**Comment by tadachi** [comment]
Yes, just want to chime in,

https://api.twitch.tv/kraken/search/streams?q=starcraft 

is returning 0 results for my home IP and my server IP.

**Comment by PyroPope** [comment]
Seems to be working again... I'm going to go ahead and mark it as closed for now.

**Comment by alanebro82** [comment]
Yeah, I'm getting some results now, but they're pretty bad.  1-2 per stream search, instead of the 10 I'm asking for.

They also don't appear to be the highest viewers first.

**Comment by absolutejam** [comment]
I'm getting results with the above format (replaced starcraft with hearthstone), but if I use `limit=10` it seems to be giving me 10 of the top streamers (still in order of viewers), but not **the** top 10.

So if I compare it with the website's list, it would maybe give me streamers number 3, 5, 6, 8 (and so on) 
of the top streamers for this game, in order of most viewers, and it gives the same streamers every time.

Is this an issue that could be related, or am I just doing something wrong or expecting something different to what the results are providing?

**Comment by PyroPope** [comment]
Seems good now, likely has been corrected since last night.
Yea the list is ordered by viewers, but it doesn't give the top viewers all the time.

I actually prefer it that way for the way i use it. But yea the results I am getting now seem to be inline with the way it has always been.

**Comment by Fugiman** [comment]
Search results are ordered by relevancy, not viewer count. If you're looking to replicate site functionality, you'll want to use `/kraken/streams?game=Starcraft`

Anyway, seems the issue is resolved now. Thanks for the report!
