### ISSUE TITLE
Add expires_on and updated_at item for subscription object

### ISSUE THREAD

**Issue by Defman21** [justintv/Twitch-API#432]
I just don't get how to calculate the date when the subscription expires. There is only `created_at` item which contains the date when the user become a subscriber, but there is no `updated_at` and `expires_on` items which should contains the dates when the subscription was renewed and when the subscription benefits will no longer works for the user.

**Comment by saladin1980** [comment]
If i am not mistaken (which i could be)  that updates once they renew so you will have to find out how long the subscription is for.. Not all to familiar with the subscriptions as of yet. It will also remove that and be blank if they are no longer subscribed to you.

**Comment by Defman21** [comment]
It's not. I've subscribed to `user_blablabla` at `2015-06-24T09:04:31Z` and renewed it a month ago, but it still gives me `2015-06-24T09:04:31Z`. (using `/users/:user/subscriptions/:channel` method)

**Comment by trumpi** [comment]
Hey Defman21

I like this idea and I am really keen to see Twitch implement this.

**Comment by saladin1980** [comment]
If your subscription has lapsed is it still showing on the information that is passed to us through the api ... that would be the only way to know without a doubt. Or if twitch stuff gives us the answer to it..

**Comment by Defman21** [comment]
I've cancelled my subscription to a user but it still shows me that I'm a subscriber. I don't know what is the reason to provide 3 additional days of benefits, but it's annoying that there's nothing in the info I get via `/users/:user/subscriptions/:channel` method in this case. `expires_on` and `updated_at` is something that Twitch **must** include in their subscription object or at least change `created_at` when the user updates his subscription.

**Comment by 099io** [comment]
+1, I think this would make it easier to find out when a user can be subscribed until and when they last resubscribed.

**Comment by BarryCarlyon** [comment]
@Defman21 you get "3 days of benefit" as when you pay, you pay for the following 28 days (or so)

"Cancelling" a subscription just means that it will not auto renew on the given date.
You don't get a refund for the 3 "unused" days of subscription, and you remain a Subscriber until the renewal day.

So a "cancel" is an instruction to the payment service to cancel the recurring subscription/payment agreement.

That said, I can see the ```expires_on``` being useful, BUT there would only be a ```expires_on``` if a user has marked their subscription as not to renew, and there might be some privacy/contractual issues on that one.
In this case the ```updated_at``` doesn't make sense, as the subscription wasn't updated (you could say it updates on the day of payment but thats another issue)

**Comment by Defman21** [comment]
Yeah, there could be some privacy issues, but I hope that Twitch will found a good way to implement it. It's hard to provide some stuff for subscribers because the only one way I can see is fetching subscribers list once at day and add new subscribers and remove users that are not subscribers anymore.
(btw sorry for my English, I'm from Russia and I'm learning English atm)

**Comment by TournyMasterBotCurse** [comment]
@BarryCarlyon  I think the intent of 'expires on' would be 'Expected to not renew on' which would allow you to mark when a sub is expected to renew (or not) and allow you to recheck. But ultimately, this information is available either way (provided you have access to subscriber data, which they would in this instance) and would help the broadcaster understand how their income might be impacted on any given day.

**Comment by BarryCarlyon** [comment]
I can see how that would be more useful, along with a indicator of the number of months a person has been a sub also…

See also #347
