### ISSUE TITLE
Get stramers list even offline

### ISSUE THREAD

**Issue by dkonopka** [justintv/Twitch-API#439]
Is there possibility to get list streamers (even offline) from country/language?

And for example with more than >1000 followers?

**Comment by freaktechnik** [comment]
When a channel isn't streaming you can still get all info that is relevant while it is offline by calling the channel endpoints.

**Comment by dkonopka** [comment]
Hm, still looking for opportunity. Im getting online streamers from 

https://api.twitch.tv/kraken/streams?broadcaster_language=es,

but https://api.twitch.tv/kraken/channel?broadcaster_language=es isnt working so well..
