### ISSUE TITLE
Load chat over https

### ISSUE THREAD

**Issue by Alex-Nabu** [justintv/Twitch-API#441]
Hello.

I noticed you guys have been hinting at doing some work to support both video and chat via https. I managed to find some what I suppose to be beta version of loading the stream via ssl but still nothing for the chat. Is there a way currently I can load the twitch chat over https. Or at the very least through some means that allows my users to feel safe (nice lock). 

Thanks very much for taking the time.

**Comment by TournyMasterBotCurse** [comment]
You can use the new websocket chat to load chat over SSL

**Comment by Alex-Nabu** [comment]
There is nothing in the documentation can you please provide me a link so I can read how to do so. Thanks very much for the reply

**Comment by TournyMasterBotCurse** [comment]
Sure,

An example channel chat properties:
http://api.twitch.tv/api/channels/lirik/chat_properties

The above uses 'Lirik' as the test channel.

There is a list of chat_servers, and socket_servers - each of these is the web client ip and port, any ip that ends in :443 is SSL. (All servers support 6667 for normal IRC communication)

**Comment by Alex-Nabu** [comment]
Forgive I haven't worked with the twitch api much beyond using your html5 iframes. Will I have to implement some form of irc client on my website to use the chat now? I'm guessing simply replacing the urls with one of the provided ip chat servers isnt going to work. A tutorial of some kind would be nice. These things really should be placed in the documentation. Thanks for all your help.

**Comment by Alex-Nabu** [comment]
thanks
