### ISSUE TITLE
Display Stream in native mobile apps without deep linking into Twitch app

### ISSUE THREAD

**Issue by nightshiftdev** [justintv/Twitch-API#443]
Is is it possible to display twitch stream directly from my mobile app (i.e.: on iOS using Media Player Framework) without deep linking into Twitch app? If yes, what API call returns the URL to the stream? If no, are there future plans to enable direct stream access?

Thanks

**Comment by kokarn** [comment]
Well you could play the hls stream locally, apart from that i don't know
any way to to it currently.

**Comment by nightshiftdev** [comment]
thanks kokarn, this helped me to get on the right track...

do you know how to get retrieve m3u8 hls access to twitch streams?

i.e.: from 

http://www.twitch.tv/professorbroman/hls

into:
http://video18.dfw01.hls.ttvnw.net/hls-a08331/professorbroman_16694372784_316387858/mobile/py-index-live.m3u8?token=id=818447284189764438,bid=16694372784,exp=1443633997,node=video18-1.dfw01.hls.justin.tv,nname=video18.dfw01,fmt=mobile&sig=7062a8ee0b6fa9638490c487d0d3c782c27c7c6f

It seems Safari, Mobile Safari and VLC are able to do that...

**Comment by bashtech** [comment]
Accessing the HLS playlists directly is not supported and is technically a ToS violation for a 3rd party app. You will need to use one of the provided embed player (/embed, /hls, or Flash).

**Comment by nightshiftdev** [comment]
Thanks bashtech, I would definitely like to use provided embedded players. Unfortunately I am unable to find the way to do this on Apple tvOS.

**Comment by imjakechapman** [comment]
BUMP on this topic. Any forward progress on direct stream access for Apple TvOS? @bashtech
