### ISSUE TITLE
Stream search API

### ISSUE THREAD

**Issue by josephcricket** [justintv/Twitch-API#444]
The search/streams API has been working in a strange way since 2 days ago. It's a problem that I noticed happens from time to time, but it's usually fixed quickly.

The problem consists in the fact that every search with more than 1 term returns all the results available for each term, not all the results which contains all the terms. Basically, no matter how many terms you specify in the search, the engine interprets it as a logical OR, not a logical AND. That makes it very difficult to refine searches, since you cannot search for multiple terms at the same time without getting a lot of noise results.

Example: if I search for "Star Citizen" I will get a gazillion results from starcraft, starmade, starbound and every single stream that contains that substring in the title, when i was aiming to get result just from "Star Citizen" streams.

This is happening only in the search/streams endpoint. The search/channels appears to be working fine.

**Comment by Fugiman** [comment]
If you surround the query in quotes (`query="Star Citizen"`) or use the `AND` operator (`query=Star AND Citizen`), I believe you'll get what you want.

**Comment by josephcricket** [comment]
Wow, the AND thing works just perfect! 
Thank you!
