### ISSUE TITLE
profile_banner

### ISSUE THREAD

**Issue by Streusel** [justintv/Twitch-API#448]
The profile_banner url from https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channel doesn't work.
"profile_banner": "http://static-cdn.jtvnw.net/jtv_user_pictures/test_channel-profile_banner-6936c61353e4aeed-480.png",

**Comment by Decicus** [comment]
That's just an example. If a "profile_banner" isn't set, it's simply set to NULL.
