### ISSUE TITLE
Authentication on tvOS

### ISSUE THREAD

**Issue by gdavis** [justintv/Twitch-API#449]
Following the API documentation regarding using OAuth2, it seems we are unable to authenticate a user using tvOS since there is no web view available. How do we go about authenticating users for requests under this new platform? Are there any legacy APIs we can make use of to support this?

**Comment by belthesar** [comment]
Most devices of this nature use a discovery service for this.  The app
checks in with the service, which issues it a short serial number.  On a
browser-enabled device, this code is entered into a portal that you are
authenticated to, and that builds the OAuth trust.

**Comment by gdavis** [comment]
Thanks for the reply @belthesar. Are you referring to a solution similar to what this article describes? http://stephenradford.me/oauth-login-on-tvos/

**Comment by DallasNChains** [comment]
OAuth login is the correct way to go about this. In the future, I would suggest asking questions like this in the [Twitch Developer Forums](https://discuss.dev.twitch.tv).
