### ISSUE TITLE
Twitch API v2 problem

### ISSUE THREAD

**Issue by mca64** [justintv/Twitch-API#451]
Mostly respond will be V3, sometimes V2

**Comment by TournyMasterBotCurse** [comment]
Be sure you're passing the web request accept as application/vnd.twitchtv.v3+json

**Comment by mca64** [comment]
im sure

**Comment by bashtech** [comment]
Which specific endpoints?

**Comment by mca64** [comment]
i was getting 'broadcaster' for long time (one year?). Now very rare is possible to get this.

**Comment by mca64** [comment]
i use this code https://github.com/mca64/mca64Launcher/blob/master/ListaStrumieni.pas  to get V2 and V3 for well until now

**Comment by Fugiman** [comment]
Fixed
