### ISSUE TITLE
Possibility to trigger /host via API

### ISSUE THREAD

**Issue by kirbo** [justintv/Twitch-API#454]
Related to: http://blog.twitch.tv/2014/07/host-mode-faq/

I would like to be able to switch the channel i want to host on my own channel via API. Can it be done?

**Comment by scagood** [comment]
It cannot be done directly in the API but you can put a small script onto a web server that connects to the IRC and performs the host command then disconnect.
Unfortunately this is rather resource inefficient but it is the only way I could think of when I came across this problem, also this means you'll have to make calls to another server too.

I can post my version of this in PHP and Node JS tomorrow if you want it or sudo code if you want to come up with your own version.

If anyone else has a better suggestion I'm all ears.

Hope this helps
Sca

**Comment by kirbo** [comment]
I've been implementing a workaround for this by using Hubot on twitch channel, since i need it to other stuff too, but it feels like this should be possible to do via API so that one shouldn't have to create extra scripts and/or bots or stuff in order to swap host.

**Comment by DallasNChains** [comment]
There isn't a supported way to do this through the API. We'll document it if it becomes available in the future! :)
