### ISSUE TITLE
How do I know the name of the auth user?

### ISSUE THREAD

**Issue by johnRivs** [justintv/Twitch-API#456]
I managed to set up authentication and there's something that is flying right over my head.

I want to store the name of the user that just went through the auth process and associate the access token to said user. **How is my app supposed to know the name of the user I got an access token of, right after I get the token?**

I was thinking about making a request to `/channel` passing the token, but that requires the `channel_read` auth scope, which I don't really need for my app. Is there no other way?

**Comment by bashtech** [comment]
The root (https://api.twitch.tv/kraken) will provide username as well has
auth status.

**Comment by johnRivs** [comment]
@bashtech That's exactly what i needed. Thanks very much1
