### ISSUE TITLE
[Bug] Reworked /streams endpoint bugs out on client_id param

### ISSUE THREAD

**Issue by moocat** [justintv/Twitch-API#457]
So apparently after the /streams endpoint got recently rewritten it no longer takes a client_id parameter.
It acts like "normal", but shows the stream as offline when it's really online.

With:
https://api.twitch.tv/kraken/streams?channel=bobross&client_id=e35gnrxztsw5nocsje75p93hlq4hkkn
Without:
https://api.twitch.tv/kraken/streams?channel=bobross

Looks like this is a reoccurring bug, which broke again recently:
https://github.com/justintv/Twitch-API/issues/69
https://github.com/justintv/Twitch-API/issues/281

**Comment by Fugiman** [comment]
As per [the documentation](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streams), this is expected behavior and not a bug.
