### ISSUE TITLE
Disable selection on twitch player

### ISSUE THREAD

**Issue by Den-dp** [justintv/Twitch-API#465]
I am used to open stream in full screen by double clicking. But this cause unnecessary text selection on the right top corner (Chrome).

![image](https://cloud.githubusercontent.com/assets/1770529/11163555/b7c6eb2e-8adc-11e5-9dde-59194dc880b8.png)

But it's simple to fix

```
.player-hover.player-livestatus.js-livestatus {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

P.s.: I'm not sure I fired issue in correct repo...

**Comment by fisherinnovation** [comment]
IMO - just title and game text should be selectable, incase I wanted to copypasta it out to someone/chat etc.. The channel image should not be selectable either should anything else in the controls.
