### ISSUE TITLE
Unban this channel pls twitch.tv/etozhemad

### ISSUE THREAD

**Issue by GreyGoaT** [justintv/Twitch-API#468]
Pls see that petition and unban -->> https://www.change.org/p/support-twitch-tv-unban-channel-etozhemad-and-give-us-a-public-apology

**Comment by codepoet** [comment]
This GitHub repo is for developers using Twitch API, not general support. Twitch support can handle your requests, you'll need to ask support team for help at http://www.twitch.tv/contact
