### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by SeanaldTrump24** [justintv/Twitch-API#473]
This may or may not be the correct forum to post this, and if it isn't I apologize, but I was directed here.  I'm looking for someone to write a script for a reddit page that will show if a specific person is currently live on Twitch.  I've seen reddit pages with this in the sidebar, but have been unable to find anything available to download.  Please let me know if anyone can help.  Thanks.

**Comment by cgwic** [comment]
as example:
https://api.twitch.tv/kraken/streams/starladder_hs_en
if stream offline then stream value is null
[link to doc](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel)

**Comment by SeanaldTrump24** [comment]
Yes, exactly.  Now, um, how do I take this from here and make it usable for what I want it for?

**Comment by cgwic** [comment]
@SeanaldTrump24 
[here](https://gist.github.com/cgwic/4ff7757dbfa7d9058c22) very simple example
use: "index.html?name=starladder_hs_ru" or "index.html?name=trump"

**Comment by SeanaldTrump24** [comment]
Ok, so all I need to do is copy and input the correct address for it to pull the info from?  Then paste into the correct place on Reddit?

**Comment by cgwic** [comment]
yes, its just example
u can use hardcoded links and display apropriate info
