### ISSUE TITLE
Add documentation for followed games

### ISSUE THREAD

**Issue by mccxiv** [justintv/Twitch-API#476]
You can find a user's followed games here: https://api.twitch.tv/api/users/k3nt0456/follows/games but it does not appear to be documented here: https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md

I didn't PR because I don't know what parameters it takes

Thanks to @decicus on r/twitch's Discord for pointing out it exists

**Comment by freaktechnik** [comment]
Only kraken endpoints are documented. /api endpoints are "inofficial" endpoints.

**Comment by Fugiman** [comment]
We don't document `/api` endpoints, as they are not built for public use.
