### ISSUE TITLE
Application Revoke Access

### ISSUE THREAD

**Issue by sweptsquash** [justintv/Twitch-API#479]
Is it possible to make a request to the API that revokes a user’s access to an application? Rather than having them going to their Connections Tab under their Twitch Account to remove said application.

I found this post https://github.com/justintv/Twitch-API/issues/333

Which refers to making a DELETE request to https://api.twitch.tv/kraken/oauth2/authorization/CLIENT_ID?oauth_token=OAUTH_TOKEN

However, I receive Bad Request when attempting this, looking on Twitch this is the same process used under the connections tab just made by jQuery’s Ajax Post method. 

Any help would be deeply appreciated.

**Comment by TournyMasterBotCurse** [comment]
Currently the end user has to disconnect the app manually (which sucks) - but it's the only way to revoke oauth tokens.
