### ISSUE TITLE
Twitch API doesn't give me the current profile banner

### ISSUE THREAD

**Issue by KD76** [justintv/Twitch-API#490]
Hello everyone,

I tried to use v3 API to get the profile image of [this user](https://www.twitch.tv/phxdefcon/profile), which is currently [this one](https://static-cdn.jtvnw.net/jtv_user_pictures/phxdefcon-profile_banner-769c87b1822dc119-480.jpeg).

But with kraken API, I get [this result](https://api.twitch.tv/kraken/channels/phxdefcon) which give [this picture](https://static-cdn.jtvnw.net/jtv_user_pictures/phxdefcon-profile_banner-99c6c8813f4a6e69-480.jpeg). (I'm using 'profile_banner' field.)

How is this possible ? Am I doing something wrong ?

**Comment by patrickdappollonio** [comment]
Probably the Twitch API cached somehow the results, and you got an old image? I can see it now working just fine.

**Comment by DallasNChains** [comment]
This was likely a caching issue. Let me know if you still have this problem!
