### ISSUE TITLE
Embed player.  404 Not found.  Code: NoSuchKey

### ISSUE THREAD

**Issue by nicnash** [justintv/Twitch-API#498]
Trying to get the[ embedded player ](https://github.com/justintv/Twitch-API/blob/master/embed-video.md) workin, but get an error

Code: NoSuchKey
Message: The specified key does not exist.
Key: production/js/index.html
RequestId: 3ADF388849B83E35
HostId: E7UCOd9BsYIgDkCcjSySCu5ht7PMH1I00wicqVTRKVIwaqqZyERz+1xAgxfyq2M9Pw6InoZnJGw=

Here is a [JSFiddle](https://jsfiddle.net/g89ns6av/1/)

This is a AWS s3 issue.  it looks like it is looking for production/js/index.html (which might be wrong url?)

**Comment by mrjumjum** [comment]
We are aware of this issue, and are working on fixing it.

**Comment by mrjumjum** [comment]
Hotfixed.

**Comment by nicnash** [comment]
more l like Hot damn.  Thank you! This is huge!  Don't know how happy this makes me =D
