### ISSUE TITLE
Connecting to every Twitch IRC channels

### ISSUE THREAD

**Issue by martin-mh** [justintv/Twitch-API#503]
Hi !
We are creating an app who monitor every IRC channels of streams on Twitch. We are facing some issues.
In order to join every IRC channels, we have to create multiple connections to the IRC server else it simply don't work. I've limited 10 channels to each connections because we got more instabilities over that limit.
However, all of theses connections still unstable and we can't be sure we handle every messages. On an DO server we get 5000 messages/minutes and on Cloud9 we get 12000 messages/minutes with same code. So, how can we get a stable infrastructure ? Is it possible ? Thanks.

Source code is here if needed : https://github.com/vanila-io/twitch-chat-stats

**Comment by DallasNChains** [comment]
I would recommend asking these types of questions on the [Twitch Developer Forums](https://discuss.dev.twitch.tv).
