### ISSUE TITLE
Embed iframe autoplay="false"

### ISSUE THREAD

**Issue by vaseker** [justintv/Twitch-API#505]
Seems `autoplay="false"` isn't working on iframe.
[Example](https://next.survarium.pro/streams/twitch)

**Comment by Fugiman** [comment]
`autoplay=false` is not an attribute on the IFRAME, but on the url. You want `https://player.twitch.tv/?autoplay=false&channel={channel}`

**Comment by vaseker** [comment]
@Fugiman thanks.

**Comment by Oted** [comment]
@vaseker my bad, was still passing it in to the iframe. 
thanks :+1:
