### ISSUE TITLE
New Player - get online status?

### ISSUE THREAD

**Issue by Argus9** [justintv/Twitch-API#508]
Hi, first off, great job on the new interactive player - it's a huge step forward.

Is there a way to detect whether a player's channel is online or offline? I see the "isEnded()" method but it returns false, even for offline channels. I'm guessing this is only set to "true" if a channel goes from online to offline during the lifetime of the player.

Additionally, is there an event listener for when a streamer goes online?

**Comment by bofinbabu** [comment]
Any leads ?

**Comment by tmaneri** [comment]
You can use the streams endpoint to detect if a channel is live or not.

**Comment by jzisserJg** [comment]
That's what I'm currently using, but there's a noticeable delay between noticing the stream go offline in an embedded player and the API returning that fact. Being able to grab this info from the player - maybe based on whether or not the embedded player is playing something - would be better.

**Comment by Argus9** [comment]
That's what I'm currently using, but there's a noticeable delay between noticing the stream go offline in an embedded player and the API returning that fact. Being able to grab this info from the player - maybe based on whether or not the embedded player is playing something - would be better.

**Comment by bofinbabu** [comment]
@Argus9 : I've noticed the same too. I tried to fetch contents of the channel's url and parsed it to see if there's any difference while the channel is live and when it's offline. But couldn't find any.

**Comment by Argus9** [comment]
Closing issue; you can use `addEventListener` to detect when a stream comes online or goes offline.
