### ISSUE TITLE
Picture Messed Up (Only for one user in the room)

### ISSUE THREAD

**Issue by bburg321** [justintv/Twitch-API#509]
Hello,
Recently started using andchill.tv, whenever i try to watch a stream, part of the picture gets frozen like this: https://gyazo.com/9b94cfaa7b7673d94b37a2cf6a9e5821
it is not the end of the world for watching the stream, but it is very annoying.
Multiple people are in the room viewing, only i get this issue.

**Comment by Fugiman** [comment]
I suspect this is due to andchill's integration performing CSS3 transforms on the embed player. If you can replicate this on twitch itself, please let us know.
