### ISSUE TITLE
GET /channels/:channel/videos broken (and possibly other endpoints?)

### ISSUE THREAD

**Issue by ChaosCom** [justintv/Twitch-API#512]
1. The _total field returned doesn't contain the total number of past broadcasts for a given channel as documented on https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-channelschannelvideos anymore, and instead returns the total number of returned videos (i.e. is affected by the limit parameter, for example). I believe this is a regression introduced by trying to fix Issue #504.

2. What is the point of having API versioning via `Accept: application/vnd.twitchtv.v<VERSIONNUMBER>+json` if older API versions are being affected by regressions as well? (I.e. why are you guys messing with older API versions and risk introducing the same regressions into former API versions as the most current API version?

**Comment by DallasNChains** [comment]
I don't see this happening any more. Let me know if you still see it! :)
