### ISSUE TITLE
HTML5 stream [object MediaError]

### ISSUE THREAD

**Issue by 0x24D** [justintv/Twitch-API#516]
I have been using the new Brave browser release (0.8.1) which allows you to view twitch.tv streams via HTML5. Every so often I receive a black screen and an error message: [object MediaError].

I have raised this with Brave and they suggested that I should cross post it here since it it possible that it is a problem on twitchs end.

brave/browser-laptop#1139

![screenshot_2016-03-21_00-25-45](https://cloud.githubusercontent.com/assets/8465663/13908524/e88adf58-eefb-11e5-9978-ce9b76ae921b.png)

**Comment by cezaraugusto** [comment]
Hey Twitch team, any position regarding this issue? Brave users ❤️  Twitch
