### ISSUE TITLE
/channels/:channel/follows endpoint bandwidth limited / throttled?

### ISSUE THREAD

**Issue by QwisoDev** [justintv/Twitch-API#524]
I'm working on a node script which can return a list containing all streams per game having viewers > 10. Currently it runs in about 40 seconds at primetime hours  
The data streamed back to me is at an avg rate of ~7-10Mpbs  

However, when I apply the same logic towards fetching a user's list of followers, up to the 1600 offset max if available, the data returned comes at a rate of ~250-300kbps -- and I'm requesting FAR less of it per call (~680bytes)

Is this intended? Did I mess up my code somehow?

**Comment by bashtech** [comment]
Probably caching. Streams is a heavily used endpoint while followers is not. Your follower queries by be hitting a backend database for many of the requests.
