### ISSUE TITLE
streams/summary with optional game reports 0 channels and viewers for everything.

### ISSUE THREAD

**Issue by thingdeux** [justintv/Twitch-API#528]
streams/summary with optional game reports 0 channels and viewers for everything.

For the last couple of days this resource has returned 0 / 0 for every game.  First reported to me by my users on March 30th.

Examples:

https://api.twitch.tv/kraken/streams/summary?game=Street+Fighter+V

Always returns response code 200 w/ the following:

["viewers": 0, "_links": {
    self = "https://api.twitch.tv/kraken/streams/summary?game=Street+Fighter+V";
}, "channels": 0]

**Comment by bashtech** [comment]
It's not just for individual games, the whole endpoint is broken:

https://api.twitch.tv/kraken/streams/summary

```
{"channels":5,"viewers":0,"_links":{"self":"https://api.twitch.tv/kraken/streams/summary"}}
```

starting on March 31st: https://s.xg.gs/s/225-FNa86S7G5t6uQc.png

**Comment by bendada3** [comment]
yea, I have same problem with streams/summary, wrote email on support and forum, but no response. I rly need to fix it ASAP :/

**Comment by chambo-e** [comment]
This appear to be fixed since a few hours according to https://stats.twitchapps.com/

**Comment by bendada3** [comment]
its working,nice :+1:

**Comment by thingdeux** [comment]
All good. Thanks ladies and gents.
