### ISSUE TITLE
Game object logo doesn't exist on new games

### ISSUE THREAD

**Issue by clcanela** [justintv/Twitch-API#529]
There is a problem when retrieving any logo for new games (any size) since it looks like most of the old games (League of Legends, Minecraft, etc.) have their logo correctly set but newer games like The Division, Call of Duty Black Ops II have no logo and are redirected to a default image when requested. This might be a problem with the information more than a problem with the API but still. 
Here are some examples I made with different games : (**all of this values were returned by the SEARCH/games endpoint**)

- Leage of Legends http://static-cdn.jtvnw.net/ttv-logoart/League%20of%20Legends-240x144.jpg [WORKS]
- Call of Duty Black Ops III http://static-cdn.jtvnw.net/ttv-logoart/Call%20of%20Duty:%20Black%20Ops%20III-240x144.jpg [DOESN'T WORK]
- Minecraft http://static-cdn.jtvnw.net/ttv-logoart/Minecraft-240x144.jpg [WORKS]
- The Division http://static-cdn.jtvnw.net/ttv-logoart/Tom%20Clancy%27s%20The%20Division-240x144.jpg [DOESN'T WORK]
- DOOM http://static-cdn.jtvnw.net/ttv-logoart/Doom-240x144.jpg [DOESN'T WORK]

All logo URL's were both uri encoded and decoded with same results. Box art works fine on all of them
Even the logo on the example (StarCraft II Wings of Liberty http://static-cdn.jtvnw.net/ttv-logoart/StarCraft%20II:%20Wings%20of%20Liberty-240x144.jpg) works **BUT** the one from the most recent game of StarCraft II shows the default one http://static-cdn.jtvnw.net/ttv-logoart/StarCraft II-240x144.jpg

**Comment by bashtech** [comment]
When a new game is added to the database the box art and logo are not automatically added. A staff member has to manually locate and upload one. I'm not even sure where the logo image is used on the site so it's probably not broken, just that no one has added logos in a long time.

**Comment by clcanela** [comment]
It's ok, I found out that same thing while looking for more examples of recent logos in use on the site from jtv CDN and finding none. Just wanted to point this out, thanks any way
