### ISSUE TITLE
"Not You?" link on the authorization page redirects to twitch.tv instead of the login form.

### ISSUE THREAD

**Issue by PizzaBox** [justintv/Twitch-API#533]
It appears as though this is possibly caused by https://www.twitch.tv/logout?return_to=http://... not redirecting properly.

Tested on Windows 7 using Firefox 43.0.1 (0 extensions enabled), and Chrome 49.0.2623.112.

I used the http://twitchapps.com/tmi/ login page to recreate the issue, it also does the same thing for my other login pages.

**Comment by adriancretu** [comment]
This looks a lot, if not identical, to [the issue](https://github.com/justintv/Twitch-API/issues/517) I reported 19 days ago, and promptly closed a day later.

**Comment by PizzaBox** [comment]
Yeah, that looks very similar.

I've found using "https://api.twitch.tv/kraken/oauth2/authenticate?action=authorize&force_verify=true&response_type=token&client_id=...&redirect_uri=...&scope=..." forces the login page, which seems like a suitable workaround for "Not You?" not working.

 "https://api.twitch.tv/kraken/oauth2/authenticate?action=authorize..." is what "twitch.tv/logout?return_to..." is supposed to redirect to.
