### ISSUE TITLE
setChannel not working like before.

### ISSUE THREAD

**Issue by tadachi** [justintv/Twitch-API#534]
I'm using the Interactive Embed and every time I call
```
setChannel(channelname:String):void
```

It's giving me this error

![capture](https://cloud.githubusercontent.com/assets/2539962/14437655/1c5b9520-ffd7-11e5-97fb-9611717a922e.JPG)

Current behavior's setChannel is causing the error above and not changing the selected stream.

Previous behavior allowed me to keep the Interactive Embed video player without reloading it and just use setChannel() to change streams. It was very fast and it didn't have to reload the video player everytime when you change to another stream. 

Link to Interactive Embed API:

https://github.com/justintv/Twitch-API/blob/master/embed-video.md

**Comment by IceNerd** [comment]
I have just run into this as well. Hope it gets cleared up!

**Comment by tadachi** [comment]
Tried using SetChannel() at 04-15-2016 around 4:00PM PST and it's working as I thought it would.
