### ISSUE TITLE
User Endpoint returning null Email

### ISSUE THREAD

**Issue by HerrAusragend** [justintv/Twitch-API#541]
In some cases the `https://api.twitch.tv/kraken/user` endpoint is returning the Email as `null` although a valid `access_token` is transfered.
The `user_read` scope is also present.

When using the same access token with scopes `user_read` and `user_subscriptions` 

`https://api.twitch.tv/kraken/user` is still returing null email but
`https://api.twitch.tv/kraken/users/<user>/subscriptions/<target>` is not returning an authorization error.

Here are some example responses:

#### Valid Email field
```json
{
  "display_name": "User1",
  "_id": 000000,
  "name": "user1",
  "type": "user",
  "bio": null,
  "created_at": "2015-01-06T21:01:19Z",
  "updated_at": "2016-04-27T16:22:18Z",
  "logo": null,
  "_links": {
    "self": "https://api.twitch.tv/kraken/users/user1"
  },
  "email": "THIS-EMAIL@IS.VALID",
  "partnered": false,
  "notifications": {
    "push": true,
    "email": false
  }
}
```

#### `null` Email field
```json
{
  "display_name": "User2",
  "_id": 000000,
  "name": "user2",
  "type": "user",
  "bio": null,
  "created_at": "2015-03-29T12:01:11Z",
  "updated_at": "2016-04-27T16:29:19Z",
  "logo": null,
  "_links": {
    "self": "https://api.twitch.tv/kraken/users/user2"
  },
  "email": null,
  "partnered": false,
  "notifications": {
    "push": true,
    "email": true
  }
}
```

**Comment by TournyMasterBotCurse** [comment]
Has the user you're querying validated their email?

**Comment by HerrAusragend** [comment]
I dont't know. Is there a way to find this out?

**Comment by TournyMasterBotCurse** [comment]
Presumably if you're requesting OAuth tokens, you should have some form of contact with the user. If not, register a new account and test it?

**Comment by HerrAusragend** [comment]
I tested it out in the moment you replied. It seems that it's like you said that the email field is `null` if the user hasn't verified his email.
This should be added to the documentation.

**Comment by 3ventic** [comment]
Pull request #336 addresses this.
