### ISSUE TITLE
Follow/unfollow error

### ISSUE THREAD

**Issue by Cossack13** [justintv/Twitch-API#544]
Hello.

I have token and i check it. It seems like work:

https://img-fotki.yandex.ru/get/26439/9849644.46/0_dc381_ae1eb615_orig.png

but when i try unfollow any channel, i get error:

https://img-fotki.yandex.ru/get/97268/9849644.46/0_dc382_21c4744_orig.png

Can you fix it or tell me, what wrong?

**Comment by Remos** [comment]
You need the "user_follows_edit" scope while it looks like you've only requested user_read.
https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#delete-usersuserfollowschannelstarget

**Comment by Cossack13** [comment]
thank you so much!!!
