### ISSUE TITLE
Connect twitch to the streaming video I have on youtube channel

### ISSUE THREAD

**Issue by jamesdkillion** [justintv/Twitch-API#547]
Is it possible to link the streaming video I just got working on YouTube to my twitch and beam apps? I would like it if I streamed video to youtube and my other sites automatically showed the same streaming video.

**Comment by faiizow** [comment]
https://restream.io/

**Comment by thebestapp** [comment]
Hi, take a look at this one,  live streaming software for youtube - [https://yatko.com/goLive](https://yatko.com/goLive)
