### ISSUE TITLE
Thumbnail for channel picture 

### ISSUE THREAD

**Issue by Activee** [justintv/Twitch-API#549]
There is already a thumbnail option for channel preview pictures. It would be nice if a thumbnail option was there for channel pictures. Now all pictures seem to be 300x300 but that's quite big. Something like 40x40 for people who want to have a small thumbnail would be great.

Please let me know if this is a possibility in the future so I can change my code accordingly.
Edit : My bad, you can get the appropriate size by changing the url and 50x50 is available. Great

**Comment by freaktechnik** [comment]
For the record at least a few of the currently working sizes (no guarantee on them continuing to):

- 50x50
- 70x70
- 150x150
- 300x300
- 600x600
