### ISSUE TITLE
WordPress and API

### ISSUE THREAD

**Issue by DevinTheCoder** [justintv/Twitch-API#550]
So I am making a website that I want to include the Twitch API in, I want to grab the top 4 most viewed streams in a categories streamer names. Since I am new to API work I have no clue how to access these, all tough I know how to access a category. My plan is to display the top 4's streams, chats and thumbnails on my website. Any help on how to do this with WordPress would be much appreciated!

**Comment by romanzipp** [comment]
Please read the [RESTful Integration Guide](https://github.com/justintv/Twitch-API/wiki/RESTful-Integration-Guide)

**Comment by DallasNChains** [comment]
I would recommend asking these types of questions in the T[witch Developer Forums](https://discuss.dev.twitch.tv).
