### ISSUE TITLE
`GET /channels/:channel` body can contain `"mature": null`

### ISSUE THREAD

**Issue by MinnDevelopment** [justintv/Twitch-API#551]
I was parsing channel objects and got a NullPointerException from the "mature" key. I previously check if the response contains "_id" to make sure it is a proper object

**Comment by tmaneri** [comment]
I'm going to go out on a limb and guess that null means that the user has
not explicitly set wether or not their channel is mature or not, which true
and false meaning that the channel has picked a setting. I could be wrong
here, but just a guess.

**Comment by Muddr** [comment]
a lot of keys can have nulls. most defaults seems to be null unless otherwise set.

This is my bot that I never filled out the info for.  https://api.twitch.tv/kraken/channels/muddbot/

**Comment by MinnDevelopment** [comment]
Yea I figured. I'm just checking for null for everything now. It should have a default value though. And hi muddr ;O

**Comment by freaktechnik** [comment]
See https://github.com/justintv/Twitch-API/blob/ffe3ac08bb3ef43ee8d890b3b2a528ff7b619809/README.md#L58 - twitch considers everything not specifically set as blank.
