### ISSUE TITLE
All feed endpoints return 404

### ISSUE THREAD

**Issue by s1mpl3x** [justintv/Twitch-API#552]
All endpoints described in https://github.com/justintv/Twitch-API/blob/master/v3_resources/channel_feed.md return error 404.

Valid (checked with root/GET) auth-token with the channel_feed_read and channel_feed_edit scopes provided, as well as a client-id.

I guess this is related to the beta status of the whole feed thing?
If this is the case, any ETA?

**Comment by freaktechnik** [comment]
They return a 404 if the user has not enabled the channel feed beta. Generally you should look at the returned JSON and post the error message here.

**Comment by s1mpl3x** [comment]
`$ curl -H 'Accept: application/vnd.twitchtv.v3+json' -H 'Authorization: OAuth XXX' -X GET https://api.twitch.tv/kraken/feed/sykpl3x?limit=1
{"error":"Not Found","status":404,"message":null}`

feed beta enabled on that account

**Comment by bashtech** [comment]
It's https://api.twitch.tv/kraken/feed/sykpl3x/posts?limit=1

The is an error in the example block.

**Comment by s1mpl3x** [comment]
ok that was the problem, thanks!
