### ISSUE TITLE
Super small video / broken css? on age gated twitch content in iframe

### ISSUE THREAD

**Issue by jasongornall** [justintv/Twitch-API#555]
![image](https://cloud.githubusercontent.com/assets/6912393/15623847/21d5d8d6-2448-11e6-956a-c5131d73040f.png)

![](http://puu.sh/p7sSn/ec1f4ae99f.png)

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36`

**Comment by monstercatx** [comment]
![image](https://cloud.githubusercontent.com/assets/7318952/15796865/ed33f88c-29bb-11e6-8ad7-6a9de91684bc.png)
any updates?

**Comment by scottrabin** [comment]
Anything suspicious in your network tab? We've seen this happen when CSS fails to load for some reason.

**Comment by SJAnderson** [comment]
@scottrabin steve with Maestro.io here, got repro earlier today. appending [this](https://player.twitch.tv/css/player.dd0d5645dd189657e570c5166da04a9c.css) to the iframe fixed it. Didn't open network tab in time to confirm. looks like your suspicions are correct.

**Comment by MCCB129** [comment]
@scottrabin seeing this issue happen more often, can we escalate a more permanent solution to prevent this moving forward?

**Comment by mrjumjum** [comment]
@MCCB129 Can you confirm if the css is failing to load when this issue happens on your end? You can check in the network tab, or append the css to the iframe.

**Comment by MCCB129** [comment]
Confirmed, appending the css to the iframe fixes the issue.

**Comment by mrjumjum** [comment]
@MCCB129 So this means the css is failing to load. When you repro this issue, may you please check the network tab and tell me the status of the request for the css file? We are having trouble reproing this ourselves.

**Comment by MCCB129** [comment]
I took this screenshot of the network tab the last time I repro'd:
![slack-imgs com](https://cloud.githubusercontent.com/assets/11223794/16748166/6a588926-4777-11e6-98c3-818ff2e818bf.png)



Seems like nothing is loading in the network tab under CSS. I've been reproing on this test site consistently:  http://www.maestro.io/olivia39

**Comment by jasongornall** [comment]
![image](https://cloud.githubusercontent.com/assets/6912393/16748558/a4ac006a-4779-11e6-8585-f1db63608742.png)

seeing canceled css?

**Comment by jasongornall** [comment]
did some more testing and didn't see the canceled again. it just doesn't load sometimes (no visible problem in the logs)

**Comment by mrjumjum** [comment]
I am unable to repro the issue with the test link you provided. I'm on Chrome 51.0.2704.103, with no extensions installed.

To get the obvious things out of the way. 
When this issue shows up:
What browser(s) are you using?
What (if any) extension(s) did you have installed?

**Comment by Marioario** [comment]
@DallasNChains this is still happening :(

https://gyazo.com/d328bf3d4f9dc942ef043f4189805f18

reproduced on live.wgleague.net

**Comment by Marioario** [comment]
this is using chrome but the issue appears on other browsers. I do not have any extensions installed at the moment / am able to repro in incognito mode

**Comment by jasongornall** [comment]
![image](https://cloud.githubusercontent.com/assets/6912393/17672802/34a23670-62ec-11e6-9bec-16a23553800b.png)

**Comment by jasongornall** [comment]
![image](https://cloud.githubusercontent.com/assets/6912393/17672913/b80abb2c-62ec-11e6-82c5-a43fdd88344a.png)

still happening :(

**Comment by DallasNChains** [comment]
Is the reproduction link you provided still valid, @jasongornall? I can't reproduce this at all, but it might be because I'm looking at a page that isn't age gated? Unsure.

**Comment by domenvajevec** [comment]
Got repro.
![image](https://cloud.githubusercontent.com/assets/2238175/17822289/20a966b2-660b-11e6-9d71-afcf614b1306.png)

**Comment by jasongornall** [comment]
I think it was a deep level bug on our level going to close this :) thanks for the help
