### ISSUE TITLE
Streams _total is broken?

### ISSUE THREAD

**Issue by burannah** [justintv/Twitch-API#557]
Hi, 
I am new to twitch api, so probably it's a noobs question.
Sending the following request:
https://api.twitch.tv/kraken/streams?stream_type=playlist&offset=0&limit=100

Getting json with _total : 70, but streams has only 69 elements.

Does anybody knows why?

[streams_playlists.txt](https://github.com/justintv/Twitch-API/files/297841/streams_playlists.txt)

**Comment by TournyMasterBotCurse** [comment]
The total is a cached count, and the 69 elements is the data cache. The total count is cached separately from the data for whatever reason, so the counts don't usually match, but are usually within 5-10%

**Comment by burannah** [comment]
1) I don't think that Twitch is capable to cache all possible invariants for "streams" request nor it has any benefits.
2) You can test it yourself. Right now it's 64 (stream objects) to 65 (_total). Total seems always greater by one.

**Comment by jixwanwang** [comment]
This issue has been addressed and should no longer be happening. If you see it again please reopen this issue. Thank you!
