### ISSUE TITLE
TMI Chatters List Api v3

### ISSUE THREAD

**Issue by Dm3Ch** [justintv/Twitch-API#560]
Hello!
Is there an analog of http://tmi.twitch.tv/group/user/user/chatters from api v2 in api v3?

**Comment by 3ventic** [comment]
It's not a part of the documented, supported Kraken API.

**Comment by Dm3Ch** [comment]
Ok, if it is a part of not documented functions, is there anyone who could tell my what request I need or where could I find this?

**Comment by freaktechnik** [comment]
You already found it, the API surfaces of kraken are completely documented. Everything else isn't.
