### ISSUE TITLE
/streams occasionally returning 0 results

### ISSUE THREAD

**Issue by roncli** [justintv/Twitch-API#565]
Hi there!  Firstly, thanks for the API, putting it to some great use with my gaming group. :)

This is an example of a common call that I call once every minute in my app: `https://api.twitch.tv/kraken/streams?channel=sixgaminggg%2Croncli%2Cpentharian%2Csolitha0620&limit=100&offset=0&stream_type=live`

Sometimes, this call returns 0 results (it has a 200 response with empty streams, _total of 0, etc), even though a number of streamers in the list are live.  I've had to write in a check in my program to throw out 0 results unless it happens twice in a row (which is rare).

Anything I can change to get more consistent results, or is this something that needs to be fixed on your end!

**Comment by jixwanwang** [comment]
We've made some changes and are not seeing these types of issues anymore.

Can you check if this is still happening for you? If not please close this issue. Thank you!

**Comment by roncli** [comment]
Thanks, about 2 days after reporting this I noticed it stopped. :)
