### ISSUE TITLE
How to get resubs via IRC?

### ISSUE THREAD

**Issue by rutony** [justintv/Twitch-API#566]
Previously, it was possible to receive resub via IRC (from user twitchnotify). Now there is no information about them. But in chat on site I see them.
What do I need to do to get this information?

I used bot for channel and commands:
TWITCHCLIENT 3
CAP REQ :twitch.tv/tags

**Comment by freaktechnik** [comment]
See https://discuss.dev.twitch.tv/t/important-re-subscription-change/6463

**Comment by rutony** [comment]
Thank you
