### ISSUE TITLE
Twitch IRC - PRIVMSG Tags: "id" tag lacks info

### ISSUE THREAD

**Issue by brentlapierre** [justintv/Twitch-API#568]
With the recent release of cheering, and thus bits, there was also the inclusion of a new tag labelled "id", which contains a unique string of characters for every message, regardless of user. There is currently no information about this tag in the updated IRC.md file.

I'm under the assumption that this tag represents the id of the message.

**Comment by xangold** [comment]
Thanks for reaching out. This was actually added a week or two ago from another project being worked on. I'll make sure we get the docs updated. It is the id of the message as you noted.

**Comment by xangold** [comment]
Added documentation.
