### ISSUE TITLE
Interactive Player - reference player object in its event listener?

### ISSUE THREAD

**Issue by Argus9** [justintv/Twitch-API#569]
I'm writing a web application that embeds multiple streams in a page, and I'm trying to set up event listeners on each player for when the stream goes offline or comes online. I need these event listeners to be able to access information about the player they're assigned to, but I can't seem to find a reliable way to do this. It's important that the event listener be able to get the _current_ state of the player it's assigned to, because I need to know what channel is currently playing on the player.

Is there a canonical way to access info about the player when creating an event listener on it?

**Comment by DallasNChains** [comment]
Since this is already on the forums, I'm closing this.

**Comment by Argus9** [comment]
Hi @DallasNChains. Does the Twitch API team have an answer as to whether or not this is possible?

**Comment by DallasNChains** [comment]
You asked this on the forums, which is the correct place. There are responses there. That's why I closed it here. :)

**Comment by Argus9** [comment]
Understood. Thanks @DallasNChains ! :) I haven't had the chance to check the forums since yesterday afternoon so I'll give that a look.
