### ISSUE TITLE
Cheering badges

### ISSUE THREAD

**Issue by x000000** [justintv/Twitch-API#575]
Where can i get links to the bits badges ? Response from [/chat/:channel/badges](https://github.com/justintv/Twitch-API/blob/ffe3ac08bb3ef43ee8d890b3b2a528ff7b619809/v3_resources/chat.md#get-chatchannelbadges) endpoint doesn't include those.

**Comment by 3ventic** [comment]
See [the beta badge API](https://discuss.dev.twitch.tv/t/beta-badge-api/6388?u=3ventic) and the [bits tag documentation](https://github.com/justintv/Twitch-API/blob/master/IRC.md#bits-message)

**Comment by x000000** [comment]
Oh, that helped a lot! It's not a part of official API, but should be documented i believe.

**Comment by DallasNChains** [comment]
Since this isn't under api.twitch.tv/kraken/, it is an unsupported endpoint and therefore isn't documented. When it becomes a part of Kraken, it will be documented. :)
