### ISSUE TITLE
API for editting VOD information?

### ISSUE THREAD

**Issue by ajm1996** [justintv/Twitch-API#577]
I can't seem to find an API or scopes that indicate it's possible to edit VOD information, deleting VODs, etc. Is it possible to do any VOD management through the API?

**Comment by DallasNChains** [comment]
No, this isn't possible. The only operation available is [listing videos](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md). Since this isn't an API issue, I would recommend asking these types of questions in the [Twitch Developer forums](https://discuss.dev.twitch.tv).
