### ISSUE TITLE
Channel post formatting

### ISSUE THREAD

**Issue by scofield-ua** [justintv/Twitch-API#578]
Hello. What should I use for formatting channel posts? 
I'm talking about emotions, how can I replace their names with actual images?

![capture](https://cloud.githubusercontent.com/assets/1827843/16625552/cb110cca-43ad-11e6-81cb-292596deee49.PNG)

**Comment by DallasNChains** [comment]
Do you mean adding a channel feed post via the API endpoint?

**Comment by scofield-ua** [comment]
No, I mean post `body` property after getting it via API.

Ops. I found `emotes` property below `body` which contains list of emotions. How can I miss that. :anguished:
