### ISSUE TITLE
(JUST BROKE) getting blocked a frame with origin and player doesn't load

### ISSUE THREAD

**Issue by jasongornall** [justintv/Twitch-API#604]
![image](https://cloud.githubusercontent.com/assets/6912393/18405978/49e1860c-76c5-11e6-830b-9b54d2de707d.png)

seeing black screens on all iframes from twitch

<iframe style="width:1000px;height:1000px;" src="http://player.twitch.tv/?channel=monstercat" allowfullscreen></iframe>

http://www.maestro.io/ios-testing

**Comment by jwmalara** [comment]
I'm seeing the same issue

**Comment by jasongornall** [comment]
doing more testing this seems desktop only

**Comment by tadachi** [comment]
Im getting this issue as well. Very abrupt. Happened within the last 1-2 hours. Hope it gets fixed soon.

**Comment by SJAnderson** [comment]
confirmed repro on this issue.

**Comment by domenvajevec** [comment]
Broken in OSX Chrome and Firefox. Safari however works.

**Comment by bashtech** [comment]
Staff are working on a fix.

**Comment by bashtech** [comment]
Player should be fixed now.

**Comment by jasongornall** [comment]
confirmed fixed on my end thanks for the speedy response
