### ISSUE TITLE
503 on https://api.twitch.tv/kraken/streams/summary

### ISSUE THREAD

**Issue by sofigern** [justintv/Twitch-API#605]
I'm getting 503 last 3 days when try to GET https://api.twitch.tv/kraken/streams/summary. Can't find any info about this. Is it expected?  Thanks!

**Comment by Coriou** [comment]
Can't find any info either. Pretty sure it was not expected but I don't know what's taking them so long to fix this.

**Comment by DallasNChains** [comment]
We're working on a fix. I'll keep you posted!

**Comment by Coriou** [comment]
For me it's been working for the last 3 hours

**Comment by DallasNChains** [comment]
Yep! We deployed a fix yesterday. :)
