### ISSUE TITLE
emotes tag not present when receiving own PRIVMSG over the same WebSocket connection

### ISSUE THREAD

**Issue by roberthartung** [justintv/Twitch-API#613]
I created a websocket connection for chatting. But when I send a PRIVMSG I get this:

```
PRIVMSG #roberthartung :Kappa
@badges=broadcaster/1;color=#FF0000;display-name=RobertHartung;emote-sets=0,5245,6822;mod=0;subscriber=0;turbo=0;user-type= :tmi.twitch.tv USERSTATE #roberthartung
```

When looking at the actual chat WSS connection I see this:

```
@badges=broadcaster/1;color=#FF0000;display-name=RobertHartung;emotes=25:0-4;id=c9d74de5-7d5b-4ab2-bdc0-46bc243c2e43;mod=0;room-id=29723367;subscriber=0;turbo=0;user-id=29723367;user-type= :roberthartung!roberthartung@roberthartung.tmi.twitch.tv PRIVMSG #roberthartung :Kappa
```

When other users write messages, everything is fine!

**Comment by 3ventic** [comment]
The server does not echo your own messages back to you. What you have there is a `USERSTATE` message telling your status on the channel.

**Comment by 3ventic** [comment]
The server does not echo your own messages back to you; you only get a `USERSTATE` updating you on your status on the channel.

**Comment by bashtech** [comment]
Meaning you will either need to parse the emotes yourself using the emote-sets returned in USERSTATE or open two connection to the server, one for sending and one for receiving.

**Comment by roberthartung** [comment]
> The server does not echo your own messages back to you; you only get a USERSTATE updating you on your status on the channel.

It does. But it doesnt include the emotes. Why doesn't it do that? Doesn't make any sense to me!

**Comment by bashtech** [comment]
It doesn't echo back the message. You see the message as you sent if over the socket and the USERSTATE which is sent each time you perform an action in the channel but isn't the actual message thus no emotes are included.

Sent: PRIVMSG #george :This is a test Kappa
Received: @badges=moderator/1;color=#56A600;display-name=Ackbot;emote-sets=0,5,42,793;mod=1;subscriber=0;turbo=0;user-type=mod :tmi.twitch.tv USERSTATE #george

**Comment by roberthartung** [comment]
oooooh ... it says USERSTATE ... woow .. nvm then, thanks!
