### ISSUE TITLE
Streams Kraken API now asking for client_id

### ISSUE THREAD

**Issue by LifeStyler2** [justintv/Twitch-API#621]
Now that they removed client_id as an optional parameter since no one used it, it is now asking for a client ID for every request? 
https://api.twitch.tv/kraken/streams/
I use this to get list of streams but now I get this:
{"error":"Bad Request","message":"No client id specified","status":400}
Do we really need client id now for this API?

**Comment by freaktechnik** [comment]
You always need client ID for every kraken API, please see https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108 and use that for further questions.

**Comment by LifeStyler2** [comment]
DIdn't realize it changed to requiring a client ID. Thanks for pointing it out.
