### ISSUE TITLE
Embed Videos doesn't support HTTPS

### ISSUE THREAD

**Issue by pc035860** [justintv/Twitch-API#622]
Either 

``` html
    <iframe 
        src="https://player.twitch.tv/?video={VIDEO}" 
        height="720" 
        width="1280" 
        frameborder="0" 
        scrolling="no"
        allowfullscreen="true">
    </iframe>
```

nor

``` html
<script src="https://player.twitch.tv/js/embed/v1.js"></script>
<div id="{PLAYER_DIV_ID}"></div>
<script type="text/javascript">
    var options = {
        width: 854,
        height: 480,
        channel: "{CHANNEL}", 
        //video: "{VIDEO_ID}"       
    };
    var player = new Twitch.Player("{PLAYER_DIV_ID}", options);
    player.setVolume(0.5);
    player.addEventListener(Twitch.Player.PAUSE, () => { console.log('Player is paused!'); });
</script>
```

doesn't support embed on HTTPS sites after recent player change (it seems to work last week).

Insecure requests are being blocked by browser. Even VODs on Twitch site can't be played due to the blocking. e.g. https://www.twitch.tv/rikhh/v/91921506

![twitch_vod_blocked](https://cloud.githubusercontent.com/assets/811518/18951791/8cbe66fc-8679-11e6-8ad5-6699080c7d23.png)

Tested browsers: (all incognito mode)
Opera 40.0.2308.62 on Windows 10.1
Chrome 53.0.2785.116 m (64-bit) on Windows 10.1

**Comment by scottrabin** [comment]
hi @pc035860 - I'm not able to reproduce your issue locally. Can you share a link or a fiddle that demonstrates your issue?

**Comment by pc035860** [comment]
Here's the fiddle
https://jsfiddle.net/830xqy8g/

Some of the errors in my console:

![embed_error_01](https://cloud.githubusercontent.com/assets/811518/18967904/85b3ccfe-86b9-11e6-8182-266903a5d55b.png)

![embed_error_02](https://cloud.githubusercontent.com/assets/811518/18967912/8af21d7e-86b9-11e6-9a7e-2fcca2877331.png)

**Comment by pc035860** [comment]
Update: Switching off the HTML5 player from the option will fix the issue.
Lots of Twitch viewers who want to watch VODs seem to encounter the same issue.

**Comment by DallasNChains** [comment]
This should be fixed! If you see any errors with it, let me know!
