### ISSUE TITLE
streams not working

### ISSUE THREAD

**Issue by BloodWolf89** [justintv/Twitch-API#626]
The api for https://api.twitch.tv/kraken/streams/test_channel is not working.

**Comment by brentlapierre** [comment]
It should be working fine. Are you supplying your client id when sending requests to the API? That is required in order to access any and all endpoints. If so, what is the streams endpoint returning for you?

**Comment by BloodWolf89** [comment]
I am doing it how I always have. https://api.twitch.tv/kraken/streams/blood_wolf89
I get this 
`{"error":"Bad Request","status":400,"message":"No client id specified"}`

**Comment by freaktechnik** [comment]
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843 and https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108 - it doesn't work anymore like it always has.

**Comment by bashtech** [comment]
As of Sept. 14th you must supply a client ID with your request. If you do not do this you will get an error. There are instructions for registering an application to get and ID and a few code examples here: https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.nyf89gi1c****

**Comment by BloodWolf89** [comment]
Thank you all for your help. I was not aware of this change.
