### ISSUE TITLE
Get ChatSpeeds and each channels messages

### ISSUE THREAD

**Issue by mcole1976** [justintv/Twitch-API#628]
I am sorry to ask such a basic question I am working on an app that collates data from the API on chat speeds and messages. This app was getting the streams messages per minute and some chat speed data.  I am failing to find these properties on the stream.games returned JSON object.  Could you please point me to where or if I can find these please.

**Comment by freaktechnik** [comment]
It must be using IRC to count the messages.

**Comment by mcole1976** [comment]
ty i will close the issue
