### ISSUE TITLE
Search API always returns 0 followers

### ISSUE THREAD

**Issue by josephcricket** [justintv/Twitch-API#633]
I'm guessing it's some kind of error, but since this last friday/saturday the search API has been returning 0 followers for every single one of the channel objects returned as a result of the search queries.

**Comment by josephcricket** [comment]
On a side note, i've always wondered if this is the best place to report issues regarding the REST api or if it's better if we create a new topic at discuss.dev.twitch.tv?

**Comment by Dirtier** [comment]
Yea I was wondering about this as well. It does this via search --> channels and search --> streams/channel.

**Comment by josephcricket** [comment]
Soo almost 2 months since this... any updates?

**Comment by cihantas** [comment]
This happened to me today again and it's causing severe problems in my application.

**Comment by josephcricket** [comment]
Looks like it's fixed yay! thanks!
