### ISSUE TITLE
[Bug] Querying /games/top always returns a 400

### ISSUE THREAD

**Issue by DomLennonZA** [justintv/Twitch-API#635]
When using the following endpoint https://github.com/justintv/Twitch-API/blob/master/v3_resources/games.md , I always get a 400. See image below. If I use the same headers for the /streams endpoint, this works fine.

![image](https://cloud.githubusercontent.com/assets/2950221/19949038/77520088-a147-11e6-81fb-79c77daf4ec7.png)

**Comment by DomLennonZA** [comment]
Note, I have also tried adding it in the query string as different parameter names. These were client_id, clientid, and client-id.

**Comment by bashtech** [comment]
That request is working for me. Have you verified your client id is valid?

**Comment by DomLennonZA** [comment]
As mention above, I use the exact same headers when querying the /streams endpoint and it works fine.

**Comment by DomLennonZA** [comment]
I am an idiot...the was whitespace in my other request. Gonna close this now
