### ISSUE TITLE
Write Documentation for new v5 Twitch API

### ISSUE THREAD

**Issue by michidk** [justintv/Twitch-API#639]
Hi,

Twitch created a new API  (v5).
The most important change is, that the system is now using ID's instead of usernames to identify users.

You can read more about these changes here: https://blog.twitch.tv/action-required-twitch-api-version-update-f3a21e6c3410

**Comment by 3ventic** [comment]
ETA

> We’re working hard to deliver reference documentation on the affected endpoints by mid-December.

https://blog.twitch.tv/action-required-twitch-api-version-update-f3a21e6c3410#.ltdt2s45b

**Comment by DallasNChains** [comment]
https://discuss.dev.twitch.tv/t/v5-documentation-is-here/8548
