### ISSUE TITLE
Dead Link In Documentation

### ISSUE THREAD

**Issue by PaulWGraham** [justintv/Twitch-API#640]
In section [https://github.com/justintv/Twitch-API/blob/master/README.md#json-p](https://github.com/justintv/Twitch-API/blob/master/README.md#json-p) of README.md there is a link to [jsonp.org](http://json-p.org/).  The issue is that [jsonp.org](http://json-p.org/) contains no content and appears to be a squated domain.

**Comment by itbrandonsilva** [comment]
#641

**Comment by glacials** [comment]
PR merged! Thanks both!
