### ISSUE TITLE
!title command not working 

### ISSUE THREAD

**Issue by Lionphire** [justintv/Twitch-API#643]
https://gyazo.com/1416e5bcb2a3f7ba58afe8cfa12fbc26 ive asked nightbbot they dont know can anyone help?!!!!1

**Comment by brentlapierre** [comment]
This is not a support forum for third-party applications. In the future, please refrain from asking unrelated questions here.

However, to answer the question, you must do as the bot requested. Go to their website, login, and the issue will resolve almost instantaneously.
