### ISSUE TITLE
Endpoint not using IDs

### ISSUE THREAD

**Issue by SiR-DanieL** [justintv/Twitch-API#661]
FYI, I was working on a Follow button with the API, and if I use the endpoint as explained in the documentation, using the user and channel ID, it does not work.

It keeps saying that the user `1234567` and channel `987654` do not exist. Replacing them with the username and the channel name works perfectly.

Update your doc please.

**Comment by jwmalara** [comment]
Are you using V5 of the API? They are defaulting to V3 until Feb 14. You need to use the `application/vnd.twitchtv.v5+json` header on your requests.

See:
https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api

**Comment by SiR-DanieL** [comment]
OK, makes sense! Thanks!
