### ISSUE TITLE
Responsive embed

### ISSUE THREAD

**Issue by ron666** [justintv/Twitch-API#673]
What is it needed to generate a responsive Interactive Embed Video? Do I need width and height to `100%` or something else is required?

**Comment by ron666** [comment]
Nm, I figured out how: setting the DIV's width and height to 100% makes the trick. Thanks

**Comment by henrikfiedler** [comment]
Hey, I sadly have the same issue. Would it be possible for you to show me the code and how exactly you fixed? Just in case that we both don't even use the same kind of embed (I don't when this new "advanced" method from twitch came out).
Would be really happy about a reply :))

**Comment by henrikfiedler** [comment]
Okay, I might actually have found the fault I did. I'll try it when I'll be at home in several hours. I'll let you know if I fixed it on my own. (In case you'll actually read my question)
