### ISSUE TITLE
Get info by slug channels/:channel diff v3/v5

### ISSUE THREAD

**Issue by FireGM** [justintv/Twitch-API#674]
Can not get info with v5 https://api.twitch.tv/kraken/channels/test_channel. Deprecated?
I saw only about user.
And how get id channel by slug?

**Comment by BarryCarlyon** [comment]
Everything in Twitch API v5 uses ID instead of name.

See this section of the docs https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api/ on how to translate Names to ID's
