### ISSUE TITLE
twitch add og:video for twitch clips

### ISSUE THREAD

**Issue by cedvdb** [justintv/Twitch-API#681]
I didn't really know where to ask this, nevertheless Twitch should add the meta tag `og:video:url` in their header for clips. At the moment there is only `twitter:player` , it's bothering me because not everyone that shares a video is doing so on twitter. 

Look, youtube does it https://www.youtube.com/watch?v=ySTQk6updjQ
as well as `og:video:secure_url`.

Example of clip: https://clips.twitch.tv/BluePlayfulMochaMoreCowbell

Cheers

**Comment by freaktechnik** [comment]
This belongs to https://twitch.uservoice.com/forums/297558-general and not an inactive bug tracker for obsolete API documentation.
