### ISSUE TITLE
Inaccurate number of followers

### ISSUE THREAD

**Issue by vilaureu** [justintv/Twitch-API#684]
When using the API to request a list of all followers I am **not getting the right number of follower**s.

I request: _https://api.twitch.tv/kraken/channels/channelID/follows_
Therefore I am using the cursor and a _limit_ of **100**.
Using this method i make a number of requests until I have all followers.

But now the count of the followers I have requested is **2 less** than the number in __total_.

The reason is that I get two times **only 99 follower per request**.

**Comment by freaktechnik** [comment]
This belongs to https://discuss.dev.twitch.tv and not an inactive bug tracker for obsolete API documentation.

**Comment by vilaureu** [comment]
Sorry!

I simply used the link found in the documentation.

_https://dev.twitch.tv/docs/_

![grafik](https://cloud.githubusercontent.com/assets/6001480/26279033/4ed8e58c-3da9-11e7-88b7-efb95a596948.png)
