### ISSUE TITLE
Response type "id_token" not supported in OICD Implicit Auth Flow

### ISSUE THREAD

**Issue by johnmollberg** [justintv/Twitch-API#690]
I'm trying to use the [OICD Implicit Auth Flow](https://dev.twitch.tv/docs/authentication#oidc-implicit-code-flow-id-tokens-and-optional-user-access-tokens) to get information on users and following the instructions exactly (and verifying with other developer) leads to an error.

I am trying to use the url `https://api.twitch.tv/kraken/oauth2/authorize?client_id=<client_id>&redirect_uri=<redirect_uri>&response_type=id_token&scope=user_read`

This results in me being sent to the page:

`<redirect_uri>?error=unsupported_response_type&error_description=Response+type+is+not+supported`

Error description: `Response type is not supported`

I have verified that the `scope`, `client_id`, and `redirect_uri` are correct. I'm doubly certain since if I change any of them, I get different error messages.

Following the documentation, this should produce an `id_token` for me. If I try to get an access token (`token`) instead, It works flawlessly. Trying to get both (`token+id_token`) results in the same original error.

**Comment by 3ventic** [comment]
This repo isn't used anymore, use discuss.dev.twitch.tv instead. OIDC flow requires your `scope` list to include `openid`, as the documentation specifies in `scope` parameter's description.

**Comment by johnmollberg** [comment]
That was correct @3ventic . Can't believe I missed that, thank you.
